### ISSUE TITLE
Crashed while backing up TextMate files

### ISSUE THREAD

**Issue by cfr** [lra/mackup#100]
Backing up Library/Application Support/TextMate...
    Traceback (most recent call last):
      File "/usr/local/bin/mackup", line 947, in <module>
        main()
      File "/usr/local/bin/mackup", line 900, in main
        app.backup()
      File "/usr/local/bin/mackup", line 449, in backup
        copy(filepath, mackup_filepath)
      File "/usr/local/bin/mackup", line 684, in copy
        shutil.copytree(src, dst)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 205, in copytree
        raise Error, errors
    shutil.Error: [('/Users/me/Library/Application Support/TextMate/Managed/Bundles/iPhone.tmbundle/Support/objc_completion2.rb', '/Users/me/Dropbox/Mackup/Library/Application Support/TextMate/Managed/Bundles/iPhone.tmbundle/Support/objc_completion2.rb', "[Errno 2] No such file or directory: '/Users/me/Library/Application Support/TextMate/Managed/Bundles/iPhone.tmbundle/Support/objc_completion2.rb'"), ('/Users/me/Library/Application Support/TextMate/Managed/Bundles/iPhone.tmbundle/Support/SpecialRules.txt', '/Users/me/Dropbox/Mackup/Library/Application Support/TextMate/Managed/Bundles/iPhone.tmbundle/Support/SpecialRules.txt', "[Errno 2] No such file or directory: '/Users/me/Library/Application Support/TextMate/Managed/Bundles/iPhone.tmbundle/Support/SpecialRules.txt'")]

**Comment by lra** [comment]
Do you still experience the problem?

**Comment by lra** [comment]
Fixed in https://github.com/lra/mackup/commit/34b727be360f5c17396d5630ddeef12c55cb43e1
