### ISSUE TITLE
Feature question: Designate "restore" directory for new machines?

### ISSUE THREAD

**Issue by izaakm** [lra/mackup#1033]
I'm setting up a new (additional) machine, and I want to start with the settings from my old Mackup, but I want to keep them separate from this point forward. Ie, I want to have both of the following, for different machines:

~/Dropbox/Mackup
~/Dropbox/Mackup-new

I think, according to the documentation, the way to do this is on the new machine to first setup a new config file, specify the storage location (Mackup-new), and then do the restore. 

However, I was wondering if there's a way to do something like the following?

    mackup restore --source=~/Dropbox/Mackup-new

**Comment by gchamon** [comment]
You don't need that. You can create a `.mackup.cfg` in the `$HOME` directory. Mackup will read the `directory` from the config file and override the mackup directory.

So create a config file on your new machine containing:
```
[storage]
engine = dropbox
directory = Mackup-new
```

and you are good to go

**Comment by izaakm** [comment]
Thanks!
