### ISSUE TITLE
Support for Alfred

### ISSUE THREAD

**Issue by jonleung** [lra/mackup#1039]
Could you support [Alfred](https://www.alfredapp.com)? Thanks!

**Comment by vitorgalvao** [comment]
#20, #116,  #127, #405, #417, #813.

**Comment by pquerner** [comment]
You need to have the paid version for this feature tho.

**Comment by jamiew** [comment]
Closing as general mackup policy of not duplicating in-app functionality, even paid. From vitorgalvao in another ticket:

> This has been refused multiple times.
> No idea why @lra even keeps some of those open, some almost half a decade old. He doesn’t (understandably) want to support Alfred, because they offer settings sync as a paid feature.
