### ISSUE TITLE
Don't touch .ssh and .gnupg with the default settings …

### ISSUE THREAD

**Issue by a7p** [lra/mackup#109]
putting these files into an unencrypted Dropbox-Folder is irresponsible - mackup should not be irresponsible for me (and I should read documentation more careful - I know).

**Comment by doctaphred** [comment]
:+1: Just discovered this behavior after the fact, and I feel pretty violated. Even looking just now, I couldn't find anywhere in the docs that mention that this program uploads private keys by default—I certainly don't consider them "pure configuration files". Glad to see you're sold on the idea of making it non-default (#512), but please at least note this behavior in the main README and `mackup -h` until it's implemented.

Other than that, this is an awesome utility!

**Comment by MinimaxHeadroom** [comment]
I agree with all the comments above. Not clearly and *prominently* listing in the main documentation that such sensitive information as a user's .ssh folder would automatically be synced to the cloud—regardless of whether or not the user's private keys were password-protected—is incredibly careless.

Please omit this default behaviour or, at a minimum, include a prominent disclaimer.

**Comment by sqren** [comment]
I've now had to void my private key twice because of the auto-sync. I really like Mackup but don't this is a sensible default.

**Comment by lra** [comment]
TODO https://github.com/lra/mackup/issues/606

**Comment by lra** [comment]
Added a TODO for encryption: https://github.com/lra/mackup/issues/606

**Comment by lra** [comment]
just merged a PR to not sync ssh keys by default https://github.com/lra/mackup/pull/295
if anyone wants to do one for GnuPG, you are welcome.
