### ISSUE TITLE
Copying Homebrew setup

### ISSUE THREAD

**Issue by Blaisorblade** [lra/mackup#1125]
This looks extremely cool! So wondering... could this migrate also Homebrew configs? So that after I backup/restore, the new machine installs the same Homebrew config? Together with Homebrew Bundle (https://stackoverflow.com/a/39665218/53974)?

Alternatively, if that's too automatic, feel free to close this as out-of-scope, and maybe just link to Homebrew Bundle as a related tool.

**Comment by joe4dev** [comment]
You can achieve this by adding a custom Mackup config `~/.mackup/homebrew.cfg`

```
[application]
name = Homebrew

[configuration_files]
.homebrew/Brewfile
```

This assumes that you have a Brewfile (https://github.com/Homebrew/homebrew-bundle) at `.homebrew/Brewfile`.
All you need to do then is to run `brew bundle` in this directory then. (I created a shortcut alias for that: `alias bb='brew bundle --file=~/.homebrew/Brewfile'`)

Works awesome for me :)

**Comment by joe4dev** [comment]
Note that you have to manually maintain the `Brewfile` using this approach (i.e., it doesn't automatically mirror stuff installed with `brew install xyz`)

**Comment by Blaisorblade** [comment]
Guessing this is enough, thanks!
