### ISSUE TITLE
spaces in path

### ISSUE THREAD

**Issue by zappbrannigan34** [lra/mackup#1130]
zap:~ alexeykuznetsov$ cat ~/.mackup/jitsi.cfg
[application]

name = jitsi

[configuration_files]

Library/Application\ Support/Jitsi/sip-communicator.properties

zap:~ alexeykuznetsov$ mackup backup -v | grep -A 4 jitsi
--- jitsi ---
Doing nothing
  /Users/alexeykuznetsov/Library/Application\ Support/Jitsi/sip-communicator.properties
  does not exist

**Comment by zappbrannigan34** [comment]
workaround:
ln -s /Users/alexeykuznetsov/Library/Application\ Support /Users/alexeykuznetsov/Library/ApplicationSupport

zap:~ alexeykuznetsov$ cat ~/.mackup/jitsi.cfg
[application]

name = jitsi



[configuration_files]

Library/ApplicationSupport/Jitsi/sip-communicator.properties

zap:~ alexeykuznetsov$ mackup backup -v | grep -A 20 jitsi
--- jitsi ---
Backing up
  /Users/alexeykuznetsov/Library/ApplicationSupport/Jitsi/sip-communicator.properties
  to
  /Users/alexeykuznetsov/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/ApplicationSupport/Jitsi/sip-communicator.properties ...

**Comment by feigaoxyz** [comment]
no need to use `\` before space. check the examples in default apps:

https://github.com/lra/mackup/blob/c9ebcfe14836dfbd123b360757b3dfd7e3968177/mackup/applications/bbedit.cfg#L5

**Comment by Crocmagnon** [comment]
It's a bit confusing for users that are used to dealing with spaces in paths. I thought I tried everything : 
- `"path/with space"`
- `path/with\ space`
- `"/Users/username/path/with space"`

But in fact I just didn't try `path/with space`. I'll create a PR to add this to the comments in the example config file.

**Comment by lra** [comment]
Solved by #1179
