### ISSUE TITLE
.ssh files? fish terminal settings anyone?

### ISSUE THREAD

**Issue by varoudis** [lra/mackup#1136]
As the title says. Maybe include .ssh/ files?
Or you see it as a security issue?

**Comment by varoudis** [comment]
It seems that in my case it didnt sync ssh keys as it says on the tin.
So this is probably a bug report.

My system:
Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

MacOS: 10.13.3

**Comment by lra** [comment]
Try enabling ssh: https://github.com/lra/mackup/tree/master/doc#only-sync-one-or-two-application
