### ISSUE TITLE
Alfred please

### ISSUE THREAD

**Issue by heyitsnoah** [lra/mackup#116]
Pretty please.

**Comment by ismay** [comment]
What if you're not syncing with dropbox? I'm using the filesystem sync, and would still like to see this.

**Comment by lra** [comment]
If someone can get the blessing from the dev that's cool.

**Comment by vitorgalvao** [comment]
> What if you're not syncing with dropbox?

It doesn’t have to be dropbox. You can pick whatever you like, for Alfred. It also has standard directories that could be used in mackup.

Alfred’s “dad” is @preppeller on github and Alfred’s “mom” is [@vero](https://twitter.com/vero) on twitter. They’re also both very responsive on the forums.
