### ISSUE TITLE
Feature request: Allow adding apps individually

### ISSUE THREAD

**Issue by dnicolson** [lra/mackup#1197]
After the initial `mackup backup` command is performed it is a little cumbersome ([these steps ](https://github.com/lra/mackup#backup)only apply for files) to update the symlinks when new apps are installed.

I suggest that an additional argument be provided to `mackup backup` and `mackup restore`, so that an individual app can be added or removed.

**Comment by mustafawm** [comment]
+1 especially for removing individual apps i.e. I'm using SettingsSync for VSCode, but want to continue using mackup for all others.

**Comment by lra** [comment]
Did you try specifying apps to the conf? https://github.com/lra/mackup/tree/master/doc#only-sync-one-or-two-application

Or are you talking about something else?

**Comment by dnicolson** [comment]
I have not tried this, but limiting to a subset of apps is not the objective.

After an initial `mackup backup` it would be nice to add more symlinks without adding symlinks for all available apps.

Additionally, a comment was made (now removed) for the use case that you might want to remove a single app after the initial `mackup backup` command.

**Comment by lra** [comment]
So [this](https://github.com/lra/mackup/issues/611)?

**Comment by dnicolson** [comment]
Exactly, I didn't notice this before.
