### ISSUE TITLE
Option to Ignore all dotfiles in ~

### ISSUE THREAD

**Issue by ahmadassaf** [lra/mackup#1202]
Hello,

I have noticed that Mackup adds my dotfiles to the backup. I'd like to ignore any dotfile being backed up as I have a separate way to back those up and would like to limit Mackup only to application preferences. I do not wish to add all the dotfiles that I have to the ignore list .. can I have maybe a wild card pattern `~/.*` ? 

Thanks

**Comment by lra** [comment]
See https://github.com/lra/mackup/tree/master/doc#dont-sync-an-application

**Comment by ahmadassaf** [comment]
@lra I did read that and it does not resolve my issue. Please do not close the issue yet as the issue is not resolved. My question is clearly asking about ignoring all of the dotfiles that are in home not just one application. Mackup synced my aliases, .curlc file .. etc. 
 1. Is there a way not to sync the dotfiles .. ALL of them
 2. Is there a way to ignore files or folders by a pattern matching

**Comment by lra** [comment]
There is no such thing as "all dotfiles". All config files are grouped by application. If you want to not sync a given config file, you have to tell mackup which application config to sync or not.

There is no pattern matching, it's technically not possible.

**Comment by ahmadassaf** [comment]
Interesting .. makes sense that this is application specific but I still do not get why things like `.aliases` file got backed up. If pattern matching is not possible then I think I will carry on trying to understand why they were synced on my own. 

Many thanks for your input

**Comment by lra** [comment]
`.aliases` are part of the `bash` application: https://github.com/lra/mackup/blob/master/mackup/applications/bash.cfg

**Comment by javoire** [comment]
My solution to this was adding _all_ apps to the ignore list and then uncomment the ones to backup.

Copy all apps
```sh 
$ mackup list | pbcopy
```
Add to config file `~/.mackup.cfg` and backup only eg "adium"
```yaml
[applications_to_ignore]
1password-4
2do
ack
# adium
adobe-camera-raw
airmail
alacritty
...
```
