### ISSUE TITLE
Release latest version on Homebrew

### ISSUE THREAD

**Issue by joe4dev** [lra/mackup#1212]
Mackup is version `0.8.19` but the Homebrew version is outdated `0.8.18` (March 2018) https://github.com/Homebrew/homebrew-core/blob/master/Formula/mackup.rb

Maybe automate the release process (based on https://github.com/Homebrew/homebrew-core/pull/25657)

**Comment by lra** [comment]
Would be cool but this one would require a little more work, as mackup can now run with python3.

**Comment by lra** [comment]
Done in https://github.com/Homebrew/homebrew-core/pull/31649
