### ISSUE TITLE
Why mackup change files' permission

### ISSUE THREAD

**Issue by hujianxin** [lra/mackup#1215]
I have some executable script sync with mackup, when synced, these files will not be executed

**Comment by lra** [comment]
Try to sync a folder with your execs in it (e.g. `~/bin`)?

**Comment by hujianxin** [comment]
@lra Also not work

**Comment by lra** [comment]
If you sync a folder and not the files within it, mackup does not change the files permissions. Make sure you sync a folder and not files.

**Comment by hujianxin** [comment]
@lra thanks

**Comment by hujianxin** [comment]
I synced a folder, but mackup does change the files permission......

**Comment by lra** [comment]
My bad you are right, but it's this way because some file syncing engine and some OS mess up with the permissions (e.g. make some file executable, or world readable), and unless we find time to write specific code for each engine, the default has been to just make every folder and file read/write for the current user only.

**Comment by davidfmatheson** [comment]
This bites me whenever I run `mackup backup`. I use Mackup, zsh, oh-my-zsh Git functionality, and powerlevel10k theme. If you run into problems with gitstatus, just use:

`chmod +x ~/<your cloud drive>/Mackup/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-*`

**Comment by roman1gan** [comment]
When I copy any file (mackup backup -> file_system), their permissions totally reset to 700, and don't resore (when mackup uninstall)...

**Comment by davidfmatheson** [comment]
@hujianxin did this issue go away for you? I can retry with the current version, if so.

**Comment by hujianxin** [comment]
@davidfmatheson I don't use markup as for now, sorry for that.

**Comment by MahdiNazemi** [comment]
I have the same issue on macOS and Dropbox.
Following the thread to see if there is a solution.

**Comment by MahdiNazemi** [comment]
@lra, would it be possible to reopen the issue if you think using `os.access()` has some merit?

**Comment by lra** [comment]
Removing this would require adding tests and testing it on all engines, because it was added to prevent errors when adding files with bad modes to synced folders (e.g. in dropbox) leading to errors and issues.

**Comment by jaklan** [comment]
@lra could we just add a separate CLI flag to force keeping file permissions then? Users having the above problem would have a mechanism to solve it, with a remark there's no guarantee of no engine-specific errors, the rest would be unaffected.

**Comment by weeebdev** [comment]
Any updates?
