### ISSUE TITLE
Amphetamine not working

### ISSUE THREAD

**Issue by esetnik** [lra/mackup#1216]
Every time the app is launched it resets the preferences

**Comment by lra** [comment]
Looks like it's a Mac App Store app. Chances the containers are getting in the way. @mdentinho added support for it (https://github.com/lra/mackup/pull/946), maybe he knows better?

**Comment by lra** [comment]
I agree, but I can't test every app myself, so I have to trust some. Fixed in https://github.com/lra/mackup/commit/dd53e6f355910197ebaee242aadc1e72caff2994

**Comment by esetnik** [comment]
No problem. Thanks for the great software and fix.

**Comment by JohnAJimenez** [comment]
@esetnik have you been able to repair Amphetamine? I am in the same situation where I cannot get the  settings to stick.

**Comment by esetnik** [comment]
@JohnAJimenez yes. What I had to do was unlink `mackup` using 

```bash
$ mackup restore
```

And then delete the `com.if.Amphetamine` iCloud container:

```bash
$ rm -r ~/Library/Containers/com.if.Amphetamine
```

Finally restart the computer and relaunch Amphetamine.

**Comment by JohnAJimenez** [comment]
Thank you @esetnik.
I was missing the restart step like a fool.

**Comment by head1328** [comment]
Why was the support of Amphetamine removed?

**Comment by lra** [comment]
See https://github.com/lra/mackup/issues/1216#issuecomment-419662969
