### ISSUE TITLE
Investigate FASD

### ISSUE THREAD

**Issue by joshmedeski** [lra/mackup#1219]
As per [this thread](https://github.com/lra/mackup/issues/818#issuecomment-420438962) I will be investigating if the `fasd` application is causing Mackup commands to always asking to replace the file. It will be removed from Mackup if that's the case.

**Comment by pithyless** [comment]
@joshmedeski confirming that `fasd` is causing `mackup backup` to always prompt to replace file. Just an FYI :)

**Comment by joshmedeski** [comment]
@pithyless thanks for the follow-up. I've put it in my task list and will do it in the next week!

**Comment by joshmedeski** [comment]
I'm not able to reproduce the same issue with `fasd`. I recommend we leave it as right now.
