### ISSUE TITLE
~/Dropbox/Mackup folder dependency for Visual Studio Code

### ISSUE THREAD

**Issue by bbilginn** [lra/mackup#1224]
Hi,
I've removed the Macup folder with dropbox uninstalling and my vscode app crushed. Problem as described here => https://github.com/Microsoft/vscode/issues/43506#issue-296372278
I reinstall dropbox and sync Macup folder.. it worked. I am sure, because renamed folder to Macup__ and again crush.

**Comment by dannevang** [comment]
That is to be expected, as Mackup moves the config file and symlinks it to the dropbox folder. If you remove the file it symlinks to, it won't work.

https://github.com/lra/mackup#bullsht-what-does-it-really-do-to-my-files
