### ISSUE TITLE
Visual Studio Code (OSX) installed extension list out of backup

### ISSUE THREAD

**Issue by made-with-care** [lra/mackup#1226]
Extensions didn't restore after reinstalling VSCode (OSX) on clean host.

**Comment by txemaleon** [comment]
Extensions are not synced via mackup, check #1170

**Comment by osteele** [comment]
The following adds the extensions to Mackup:

1. Create a directory named `~/.mackup`, if one does not already exist.
2. Download [this file](https://github.com/lra/mackup/files/3684261/vscode-extensions.cfg.txt) `~/.mackup`, and rename it to `vscode-extensions.cfg`.
3. If you're [whitelisting applications](https://github.com/lra/mackup/blob/master/doc/README.md#only-sync-one-or-two-applications) (your `~/.mackup.cfg` file contains `[applications_to_sync]`), add the following line to the `[applications_to_sync]` section:

`VSCode-Extensions`

**Comment by osteele** [comment]
#1170, which removes syncing, says that syncing the extensions is completely redundant.

It's not redundant, in the case where you have two machines that you want to stay in sync (installing an extension on one installs it on the other). However, the case that this shouldn't be default behavior is still reasonable.

It would be nice if there were a way to include a “VSCode-Extensions” application that was disabled by default. So far as I can tell, Mackup doesn't support default-disabled applications? (In which case it's maybe too much complexity to add that feature just to support this one case.)

**Comment by ndbroadbent** [comment]
Would it be possible to sync the list of installed extensions, and have a post-restore sync task that clones all of the git repos? (e.g. after `mackup restore`?) It's annoying that I have to keep reinstalling all of my VS Code extensions on a new machine.

Or maybe it's just better to use a dedicated tool for this: https://marketplace.visualstudio.com/itemdetails?itemName=Shan.code-settings-sync

(Article: https://itnext.io/settings-sync-with-vs-code-c3d4f126989)

**Comment by lra** [comment]
You can add a custom config to mackup to sync those files if you want. It just does not make sense to make this edge case a default for everyone.
