### ISSUE TITLE
iTunes Scripts are broken on macOS Mojave

### ISSUE THREAD

**Issue by dnicolson** [lra/mackup#1234]
Since installing macOS Mojave I noticed that if the `~/Library/iTunes/Scripts` directory is a symlink the script menu in iTunes will not appear.

I have made a bug report with Apple, however, all of the AppleScript-related bugs I have submitted over the years have not been fixed or acknowledged.

Perhaps the `iTunesScripts` configuration should be removed for the time being?

**Comment by lra** [comment]
Yeah, if it's not supported anymore, we should remove it. Want to do a PR?

**Comment by pquerner** [comment]
If its only a problem for Mojave, why remove it for all MacOSX versions?

**Comment by lra** [comment]
There is no way to specify a config per MacOS version in Mackup.
