### ISSUE TITLE
Xonsh in source but not in Homebrew or Pip installations

### ISSUE THREAD

**Issue by chewrocca** [lra/mackup#1235]
I see the application Xonsh in source but not in Homebrew or Pip installations.  Xonsh backups work when I install from source.  Can this be pushed to Homebrew?

**Comment by lra** [comment]
I just released https://github.com/lra/mackup/releases/tag/0.8.20 so it's available on pip.

For homebrew, you can submit a PR there, the community usually updates it pretty fast.
