### ISSUE TITLE
Backup for root files.....

### ISSUE THREAD

**Issue by LHY-iS-Learning** [lra/mackup#1236]
I'm trying to backup files on a Ubuntu VPS which is running as root...
Is there a way to bypass the "Error: Running Mackup as a superuser is useless and dangerous. Don't do it!"
Thanks!

**Comment by lra** [comment]
Not officially, could be an option in the future if there is enough demand.
You can patch it easily right now if you want (1 line change)

**Comment by LHY-iS-Learning** [comment]
it works
thanks for the reply
