### ISSUE TITLE
Google Drive on Linux

### ISSUE THREAD

**Issue by Christilut** [lra/mackup#1257]
I'm trying to use Mackup with Google Drive on Kubuntu but I'm not sure how this works.

I added this to my `.mackup.cfg`
```
[storage]
engine = google_drive
```

But which Google Drive am I supposed to use on Linux? There is no official client. Which unofficial client does it expect me to use? How does it know where to look?

**Comment by danielroe** [comment]
I would install any unofficial client that syncs a directory with Google Drive and then use the following:
```
[storage]
directory = MyGoogleDriveDirectory
```

**Comment by Christilut** [comment]
Thanks, I finally got around to doing this. Seems to work with `google-drive-ocamlfuse`
