### ISSUE TITLE
Why .vim/bundle is back up?

### ISSUE THREAD

**Issue by cocobear** [lra/mackup#1297]
.vim/bundle folder is very big when you install lots of plugs.
why mackup backup this folder? should we just ignore this folder by default ?

**Comment by lra** [comment]
Because someone thought it made sense: https://github.com/lra/mackup/commit/393343401f0ecae181d9d9f71298dc9c7d4eecd4

**Comment by cocobear** [comment]
`bundle` folder contains many  `git` repositories , which barely modified by user, so I think sync files which never changed is a bad idea.

**Comment by lra** [comment]
I have no opinion on the matter. Want to open a PR to remove it?
