### ISSUE TITLE
Backup .vim after

### ISSUE THREAD

**Issue by Donkeyfish87** [lra/mackup#1334]
Currently, mackup doesn't seem to copy and symlink the .vim/after folder. I guess this is a decision, but I'd argue it should be backed up by default.

In the after directory, files are executed last, ensuring that setting isn't overwritten by other files sourced. Example is filetype specific settings like `foldmethod` or `spell`.

I know it's possible to add custom files using the .mackup, however it's easy to overlook that that Mackup doesn't symlink the entire .vim folder. I assumed it did at first, which could've been embarrassing for me if I ended up losing files.

**Comment by lra** [comment]
Is the `after` folder officially endorsed by pristine VIM?

**Comment by Donkeyfish87** [comment]
I think so. If you open Vim and type `:help runtimepath`, it says Vim searches by default in a number of locations, including _the after directory in your home directory_.

See https://vimhelp.org/options.txt.html#'runtimepath'

**Comment by lra** [comment]
That's good info, thanks. Feel free to create a PR.

**Comment by Donkeyfish87** [comment]
Done. 

I guess this issue is considered closed now.
