### ISSUE TITLE
First time I use this tool, I lost all my config files

### ISSUE THREAD

**Issue by fanglijun** [lra/mackup#1337]
- When I found this tool, I was excited.

- I created a `.mackup.cfg` file to backup some config files to a git repo.

```
[storage]
engine = file_system
path = synckup

[application_to_sync]
ssh
mackup
zsh
```

- I run `mackup backup`, and found it also backup bash  config files, `.bashrc` for example, and a lot of other files

- I checked my `.mackup.cfg` file and realized I misspelled `applications_to_sync`

- I fixed `application_to_sync`, deleted all the files inside `synckup/Mackup` and run `mackup backup` again

- It says `Error: Unable to find your Dropbox install =(`

- I realized my `.mackup.cfg` file had become a broken symlink along with ALL OTHER CONFIG FILES

- 😱😱😱

- It's one and half in the morning, I'm going to sleep and start fresh tomorrow. 

- 😂😂😂

**Comment by lra** [comment]
Not sure what to do against misspellings, sorry.
