### ISSUE TITLE
Filezilla Support

### ISSUE THREAD

**Issue by matyhaty** [lra/mackup#134]
Im brand new to Mackup, but will be getting far more involed ASAP

Would be great to add support for Filezilla.
The site manager is a one file affair - XML, which is located in:

/Users/username/.filezilla/.8 (3 xml files and one queue file)

If someone can explain how that is done, I can then become way more involved, if you'll have me!!

Thanks

**Comment by lra** [comment]
TODO: https://github.com/lra/mackup/issues/606
