### ISSUE TITLE
Mackup resolves (PDF Services) links?

### ISSUE THREAD

**Issue by ashleyharvey** [lra/mackup#1348]
If I create a printing workflow (Print -> PDF -> Edit) straight to my desktop, which I often do because I want to send PDFs directly there quickly -- when Mackup gets around to backing up ~/Library/PDF Services/, it actually resolves the Desktop link and backs up my entire actual desktop rather than just treating it as an alias and backing _that_ up.

**Comment by lra** [comment]
Should we remove `Library/PDF Services`? https://github.com/lra/mackup/blob/master/mackup/applications/macosx.cfg#L7

**Comment by ashleyharvey** [comment]
I think it would be better to properly detect links and treat them accordingly. Copy the link, rather than resolving it and copying its target.

**Comment by lra** [comment]
It's not on Mackup's hands, it's just setting up links. Either it creates a link, either it doesn't. What other applications and systems do with this link afterwards is up to them.

**Comment by ashleyharvey** [comment]
I think something got lost in translation, because your reply doesn't make sense to me given what I'm reporting.

So in PDF services, there's an alias that points to my desktop.

When I run mackup and it's backing up that folder, it copies my actual desktop rather than the link.  This is what mackup does, not some other app. Mackup should copy the alias as an alias rather than resolving the alias and copying the target that the alias points to. Does that help clear it up?

**Comment by lra** [comment]
I see now.

The issue is that if I don't resolve all the symlinks, I will end up with links pointing outside the backup, and the backup won't make sense on another computer.

Allowing this can be the source of a lot of bug reports.

**Comment by ashleyharvey** [comment]
I didn't think of that.  Different username would lead to a broken link.  So the question is, which is the lesser of two evils - when Mackup backs up, should it incorrectly backup a soft/hard link or Finder alias target, or should it back up the link and risk breakage (it breaking *isn't* guaranteed as long as the setup on the other side is sufficiently replicated).  I suppose you could also build into the restore process a way to isolate links and let the user resolve them.

**Comment by lra** [comment]
> I suppose you could also build into the restore process a way to isolate links and let the user resolve them.

The amount of bug report blamed on mackup because ppl don't understand the concept of links is already too much. Making Mackup more complex is not an option.

For this type of very specific use case, I suggest making a setup for yourself on the side.

**Comment by ashleyharvey** [comment]
Thanks.
