### ISSUE TITLE
Customize existing application (issue with `PDF Library`)?

### ISSUE THREAD

**Issue by julienma** [lra/mackup#1350]
Hey,
I have an issue with the `Library/PDF Services` directory, backed up as part of the [MacOSX](https://github.com/lra/mackup/blob/master/mackup/applications/macosx.cfg#L7) application.

When this folder is a symbolic link, it seems that some applications won't find the custom entries in this folder. E.g. Apple Mail, Pages, Notes, etc. won't display custom PDF Services (but Firefox will).

Anyway, I'd like to **not** back up this `Library/PDF Services` directory.
How can I exclude it, while still keeping the other directories from the `MacOXS` application?

**Comment by lra** [comment]
You can exclude it by overwriting the `macosx.cfg` configuration.
Copy the `https://github.com/lra/mackup/blob/master/mackup/applications/macosx.cfg` file, remove the `Library/PDF Services` and add you config file to Mackup under another name, see https://github.com/lra/mackup/tree/master/doc#add-support-for-an-application-or-any-file-or-directory

**Comment by julienma** [comment]
Awesome, thanks.
Closing as it works as expected.
