### ISSUE TITLE
Critical error! Using .mackup as directory option deletes application configs

### ISSUE THREAD

**Issue by jmatsushita** [lra/mackup#1358]
I used the following config as `~/.mackup.cfg` 
```
[storage]
engine = file_system
path = /Users/myuser
directory = .mackup
```

And running `mackup backup` deleted all my application configs because [this step](https://github.com/lra/mackup/blob/master/mackup/application.py#L114-L116) doesn't check if `home_filepath` is equal to `mackup_filepath` therefore copying files to `.mackup` then deleting `.mackup`...

Thanks a lot :(

**Comment by lra** [comment]
It's an edge case, we need to make sure that a user can't use Mackup`s folder as a storage folder.

Thanks for reporting.
