### ISSUE TITLE
Can I have multiple engines?

### ISSUE THREAD

**Issue by pvinis** [lra/mackup#1360]
Like Dropbox and Local?

**Comment by lra** [comment]
No

**Comment by pvinis** [comment]
would it be easy to add?
does it make sense to add?
my idea was to have everything both in Dropbox and local for git.

**Comment by lra** [comment]
You can move your git folder in dropbox.

**Comment by pvinis** [comment]
I wanted to avoid that, as git and dropbox sometimes don't play well. Alright, thanks, I'll see what I can do.
