### ISSUE TITLE
How often are releases made, and how?

### ISSUE THREAD

**Issue by pvinis** [lra/mackup#1373]
I am guessing the answers are "whenever I have time" and "manually". Is that correct?

If yes, I'd be happy to make a CI thing for you so it releases automatically on every PR merge, or every week or two weeks or whatever.

**Comment by lra** [comment]
The main problem is that I'd need to give my pypi creds to CircleCI. How do you solve this?

**Comment by pvinis** [comment]
Circle supports env vars, we could use that.

**Comment by lra** [comment]
yes but it's not really secure if anyone can create a PR to dump those.

**Comment by pvinis** [comment]
https://twitter.com/pvinis/status/1128615519718977537?s=21

So I would say if they are used for release, we are good because them it's after a merged PR, if it's for testing, we just make some new creds and not yours.

**Comment by lra** [comment]
Might work, yes. Luckily I'm using CircleCI so there might be a way. Feel free to pick it up.

**Comment by joshmedeski** [comment]
I agree with @pvinis on this one. You should be able to use separate credentials on the master branch so none of the contributors can access it.

**Comment by pvinis** [comment]
I'll take a look in a week and a half, after my holidays. I'd like to make something here that can help us.

**Comment by Jay54520** [comment]
@lra Could you speed up this issue? The lastest realse was on  Feb 27, I have to install from the master to get the functions I need.

**Comment by lra** [comment]
Done https://github.com/lra/mackup/releases/tag/0.8.29
