### ISSUE TITLE
Mackup breaks oh-my-zsh upgrade

### ISSUE THREAD

**Issue by ileitch** [lra/mackup#1384]
I'm using the iCould engine, no other configuration.

After running `mackup backup -f`, the `~/.oh-my-zsh` is left in a dirty state, which breaks `upgrade_oh_my_zsh`.

```
➜  .oh-my-zsh git:(master) ✗ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    custom/example.zsh
	deleted:    custom/plugins/example/example.plugin.zsh
	deleted:    custom/themes/example.zsh-theme

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	custom

no changes added to commit (use "git add" and/or "git commit -a")
```

```
➜  ~ upgrade_oh_my_zsh
Updating Oh My Zsh
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
There was an error updating. Try again later?
```

**Comment by joshmedeski** [comment]
I had this issue too. This happens when you add anything to the `custom` directory (with or without Mackup`).

All you have to do is the following in the terminal
```
$ cd ~/.oh-my-zsh
$ git stash
$ upgrade_oh_my_zsh
$ git stash pop
```

Hope that helps!

**Comment by ileitch** [comment]
The directory is being created by Mackup. When I `git reset --hard origin/HEAD`, running mackup always re-creates it.

**Comment by joshmedeski** [comment]
Yes, since Mackup uses symbolic links there's no other way I can think of to achieve this. Hopefully, my steps work for you, it's a little bit of a pain but doesn't take too long.

**Comment by ileitch** [comment]
Yeah I've already been getting by by doing this. The ability to disable certain apps would be nice.

**Comment by joshmedeski** [comment]
You can choose [not to sync an application](https://github.com/lra/mackup/tree/master/doc#dont-sync-an-application) if you'd rather not deal with this issue and not backup oh-my-zsh with Mackup

**Comment by ileitch** [comment]
Ah perfect, thanks 👍

**Comment by lorenzofanchi** [comment]
@joshmedeski actually, isn't the issue that Mackup creates symlinks that cannot be stashed?

This is the error I get when trying to stash my changes:
```
rror: 'custom/example.zsh' is beyond a symbolic link
fatal: Unable to process path custom/example.zsh
Cannot save the current worktree state
```

Do you have an idea on how I could solve this?

**Comment by girishso** [comment]
@lorenzofanchi @joshmedeski 

> Isn't the issue that Mackup creates symlinks that cannot be stashed?

Yes.

I didn't want to re-install my plugins and themes, so I created a branch `my-custom`

```
git checkout -b my-custom
git add .
git commit -m "fix mackup"
git checkout master
upgrade_oh_my_zsh
git merge my-custom
```

All seems well. Hope this helps someone in future.

**Comment by leoredi** [comment]
Up

**Comment by lra** [comment]
> Up

Sorry, but what am I supposed to do? =)

**Comment by sergiodk5** [comment]
> @lorenzofanchi @joshmedeski
> 
> > Isn't the issue that Mackup creates symlinks that cannot be stashed?
> 
> Yes.
> 
> I didn't want to re-install my plugins and themes, so I created a branch `my-custom`
> 
> ```
> git checkout -b my-custom
> git add .
> git commit -m "fix mackup"
> git checkout master
> upgrade_oh_my_zsh
> git merge my-custom
> ```
> 
> All seems well. Hope this helps someone in future.

This worked for me perfectly!

**Comment by bvdputte** [comment]
> > Up
> 
> Sorry, but what am I supposed to do? =)

I'ld say - at least in the mean time until a working solution is found - remove oh-my-zsh from the mackup supported list since it breaks upgrading it?

**Comment by lra** [comment]
@bvdputte Done.

**Comment by masterix21** [comment]
Hi guys, I solved it like so:
```sh
mv ~/.oh-my-zsh/custom ~/.oh-my-zsh/custom-sym
omz update
mv ~/.oh-my-zsh/custom-sym ~/.oh-my-zsh/custom
```

**Comment by LucasLarson** [comment]
Alternatively, in `~/.zshrc`, replace this:
```shell
ZSH_CUSTOM=${ZSH}/custom
```
with this:
```shell
# assuming Mackup is in `~/Dropbox/Mackup`
ZSH_CUSTOM=${HOME}/Dropbox/Mackup/.oh-my-zsh/custom
```
([via](https://reddit.com/comments/g1a2qd/_/fneil10)).

**Comment by masterix21** [comment]
@LucasLarson it sounds much better! Yeah. Thanks.

**Comment by casey-robertson** [comment]
Hmm  - this seemed to work and now it's not.  

> Alternatively, in `~/.zshrc`, replace this:
> 
> ```shell
> ZSH_CUSTOM=${ZSH}/custom
> ```
> 
> with this:
> 
> ```shell
> # assuming Mackup is in `~/Dropbox/Mackup`
> ZSH_CUSTOM=${HOME}/Dropbox/Mackup/.oh-my-zsh/custom
> ```
> 
> ([via](https://reddit.com/comments/g1a2qd/_/fneil10)).

Also tried the git checkout, git add, git merge workflow and got this:

```
fatal: Not possible to fast-forward, aborting.
```

**Comment by k3n** [comment]
> @lorenzofanchi @joshmedeski
> 
> > Isn't the issue that Mackup creates symlinks that cannot be stashed?
> 
> Yes.
> 
> I didn't want to re-install my plugins and themes, so I created a branch `my-custom`
> 
> ```
> git checkout -b my-custom
> git add .
> git commit -m "fix mackup"
> git checkout master
> upgrade_oh_my_zsh
> git merge my-custom
> ```
> 
> All seems well. Hope this helps someone in future.

This is great, thanks for sharing. 

One problem I found though is that you can't easily upgrade the next time, since your local `master` will differ from origin, which will leave you with a mess. I solved it a slightly different way (going to use the OMZ `git` aliases, since we're in the project ;)):

```sh
gcb my-custom \
    && gaa \
    && gcmsg "My custom OMZ" \
    && gcm \
    && upgrade_oh_my_zsh \
    && gco - \
    && grbm
```

Instead of merging, I rebased my custom branch to `master`. 

Now when new commits are made to `master`, all I need to do is:

```sh
gcm && gl && gco - && grbm
```

**Comment by piotrpalek** [comment]
sorry to revive this old issue, but is there any update on oh-my-zsh support?
