### ISSUE TITLE
Advise: Make storage directory hidden itself?

### ISSUE THREAD

**Issue by madsem** [lra/mackup#1399]
What are the Pros/Cons when making the storage directory itself hidden?
I'm thinking if I should, out of fear that I would delete it accidentally in iCloud some day.
```
[storage]
engine = icloud
directory = .dotfiles
```

Is there anything that would speak against doing it like this?

**Comment by lra** [comment]
It should not impact anything, it's just a different name, it won't just show up by default.

**Comment by madsem** [comment]
@lra thanks! Then I shall do it that way :)
