### ISSUE TITLE
[FR] Add CLI command to show a given app's config

### ISSUE THREAD

**Issue by timkelty** [lra/mackup#1401]
Something I frequently do, is look for an app via `mackup list`, but before I use it, I want to look at what files it includes.

Usually this includes jumping to the codebase in github and peeking in `mackup/applications/` for the app, which gets tiresome.

It would be great if I could do this in the cli, e.g. `mackup show vim` or something along those lines, that would just output the .cfg.

**Comment by lra** [comment]
Done in 0.8.25
