### ISSUE TITLE
mackup quick action will not work

### ISSUE THREAD

**Issue by GreenHand-zmy** [lra/mackup#1403]
When use mackup quick action will not work.It will not add to system.
OS:64bit Mac OS X 10.14.5 18F203

**Comment by nuno-agostinho** [comment]
I noticed the same problem. With mackup enabled, [quick actions](https://support.apple.com/guide/mac-help/perform-quick-actions-in-the-finder-on-mac-mchl97ff9142/mac) are not being updated in System Preferences > Extensions > Touch Bar/Finder. 

After disabling mackup, the list of quick actions refreshes in real-time (you can test so by creating new quick actions using Automator).

**Comment by lra** [comment]
Then it needs to be removed from Mackup. Do you know while folder are quick actions saved into?

**Comment by nuno-agostinho** [comment]
The default folder for Quick Actions is `~/Library/Services`
