### ISSUE TITLE
Clear up confusion: Moving to new main-machine requires mackup backup or not?

### ISSUE THREAD

**Issue by madsem** [lra/mackup#1404]
Sorry if this is obvious, but the docs aren't 100% clear to me.
If I'm moving to a new main-machine, i.e I have an existing backup from mackup but formatted that old mac and move to a new one... Do I still need to run `mackup restore` only or `mackup restore` followed by a `mackup backup`?

**Comment by pvinis** [comment]
I would say `restore` is enough, but if later you add new things that should be backed up, then you do a `backup` too.

**Comment by madsem** [comment]
@pvinis ahh okay, thank you. That actually also cleared up if mackup backs up new files automatically.
I thought it was doing that because the docs say "From now on you're constantly backed up", but it seems he meant the files that existed until that point but not new files! :)

Got it now, thanks
