### ISSUE TITLE
Error running on ChromeOS

### ISSUE THREAD

**Issue by derBroBro** [lra/mackup#1407]
Hello all,

first thanks for the interesting tool!
If I try to run it in the linux system on ChromeOS I get the following error:
```sh
~ % mackup backup                                                       
Mackup needs a directory to store your configuration files
Do you want to create it now? </home/malte.brodersen/./mackup> <Yes|No>yes
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/mackup/main.py", line 89, in main
    verbose)
  File "/usr/local/lib/python3.5/dist-packages/mackup/application.py", line 26, in __init__
    assert isinstance(files, set)
AssertionError
```
If I change line 26 in application.py from `assert isinstance(files, set)` to `assert isinstance(files, (set ,list))` it works fine. I am not sure about background but the variable gets casted to a list three lines after anyway. 
Should I create a PR?

Malte

**Comment by lra** [comment]
This has been fixed in https://github.com/lra/mackup/pull/1412
Try upgrading Mackup.
