### ISSUE TITLE
Warnings from Ubuntu 18 WSL

### ISSUE THREAD

**Issue by rizkysyazuli** [lra/mackup#1422]
I'm seeing these warnings when running mackup on Ubuntu 18 installed under Windows Subsystem for Linux (WSL).

    /usr/bin/chattr: Inappropriate ioctl for device while reading flags on /mnt/c/Users/user/Dropbox/Mackup WSL/.oh-my-zsh/custom

I was backing up my Ubuntu settings into Dropbox which is installed on the Windows file system. So i'm using a custom storage configuration like this:

```
[storage]
engine = file_system
path = /mnt/c/Users/user/Dropbox/
directory = Mackup WSL
```

My files are successfully copied and symlinked to the Dropbox folder. So no complaints. Just an FYI for now.

**Comment by ahmadnassri** [comment]
confirmed on Ubuntu + WSL

**Comment by ahmadnassri** [comment]
based on a comment in StackOverflow: 

> I realize this is an old thread, but it looks likely the directories under /home are automounted nfs exports and nfs does not support chattr, lsattr etc.. You would have to set this on the nfs server's filesystem (if possible) to make the files immutable.

https://serverfault.com/questions/324975/lsattr-inappropriate-ioctl-for-device-while-reading-flags

**Comment by lra** [comment]
It might be fixed in the next release, per https://github.com/lra/mackup/pull/1040

Feel free to open this back if it's not the case.
