### ISSUE TITLE
Mackup app config files should be version independent?

### ISSUE THREAD

**Issue by captnswing** [lra/mackup#1440]
I notice two different paradigms for the config files currently in the `mackup/applications` folder. Sometimes several config files exist for different app versions. E.g.

* [Sublime2](https://github.com/lra/mackup/blob/master/mackup/applications/sublime-text-2.cfg)
* [Sublime3](https://github.com/lra/mackup/blob/master/mackup/applications/sublime-text-3.cfg)
* [appcode 2](https://github.com/lra/mackup/blob/master/mackup/applications/appcode-2.cfg)
* [appcode 3](https://github.com/lra/mackup/blob/master/mackup/applications/appcode-3.cfg)

Sometimes, one mackup app config file supports several versions of the app simultaneously. E.g.

* [IntelliJ IDEA](https://github.com/lra/mackup/blob/master/mackup/applications/intellijidea.cfg)
* [Pycharm](https://github.com/lra/mackup/blob/master/mackup/applications/intellijidea.cfg)

...I think it would be great with the latter approach (one app config file for several versions). 

This could be easier if the ini files supported wildcards in them, e.g.

`Library/Preferences/com.sublimetext.*.plist` could catch several versions of Sublime Text, and `Library/Application Support/IntelliJIdea*` would catch the App Support files for several IntelliJ versions

**Comment by captnswing** [comment]
thinking about how this could be implemented, e.g. by introducing a `deprecated` subdirectory in the `applications` folder. Then e.g. moving `sublime-text-3.cfg` and `sublime-text-2.cfg` to the `deprecated` directory and introducing an `applications/sublime-text.cfg` in their place. 

The mackup program could be changed to emit warnings and migration instructions when config files in the `deprecated` folder are found in a `mackup.cfg`

**Comment by lra** [comment]
Yeah, the multiple versions is an issue. On homebrew this is handled with a version stanza, e.g. `python` and `python@3`.

Adding optional versioning for each application is the way to go longterm.

**Comment by semkagtn** [comment]
Plese, check:
https://github.com/lra/mackup/pull/1581

**Comment by jneuendorf** [comment]
Issue #949 seems to be related as well
