### ISSUE TITLE
No issue label for new app support issues

### ISSUE THREAD

**Issue by captnswing** [lra/mackup#1444]
Suggestion:
* add a new issue label, e.g. `new app config` 
* update CONTRIBUTING.md with instructions on using that label when triaging issues
* profit?!

**Comment by captnswing** [comment]
would like to, but can make a PR with a new issue label :)

**Comment by jamiew** [comment]
@lra I'd be happy to help add labels and triage issues if I had permission

**Comment by lra** [comment]
@captnswing : There you go: https://github.com/lra/mackup/labels/new-app-config
@jamiew : invited, email me if you are in NY to get a coffee.

**Comment by captnswing** [comment]
Oh wow, took me a while to notice this update. 
Turns out, without repo permissions, I can't add new labels to tickets 🤷‍♂️

**Comment by lra** [comment]
invited.

**Comment by captnswing** [comment]
thanks for the invite. will get to it
