### ISSUE TITLE
Path Finder Error - Expected a folder, found a file.

### ISSUE THREAD

**Issue by jacobgraf** [lra/mackup#1478]
I ran a backup and now when I try to open Path Finder, I see the following error...

```
Failed to initialize the application's saved data
Expected a folder, found a file "/Users/jacobgraf/Library/Application Support/Path Finder/Settings".
```

**Comment by treee111** [comment]
same for me

**Comment by ajimix** [comment]
Looks like is a problem with Path Finder itself as it expects a folder but it finds a link file so it complains

**Comment by bosconb** [comment]
same for me +1
