### ISSUE TITLE
Add support for Rectangle

### ISSUE THREAD

**Issue by valentinocossar** [lra/mackup#1481]
Hi,

Spectacle as recently announced that [the project is no longer actively maintained](https://github.com/eczarny/spectacle#important-note).

So I'm asking if you could add support for a Swift based version of Spectacle, called [Rectangle](https://github.com/rxhanson/Rectangle).

Thank you.

**Comment by arvindch** [comment]
+1, and some additional info: As per https://github.com/rxhanson/Rectangle/issues/25, the settings are stored at `~/Library/Preferences/com.knollsoft.Rectangle.plist`.

**Comment by arvindch** [comment]
I've added a PR for this https://github.com/lra/mackup/issues/1481/
