### ISSUE TITLE
Is There a GUI Version of Mackup?

### ISSUE THREAD

**Issue by xiaochunjimmy** [lra/mackup#1498]
I love your idea and mockup,
but using config files to define sync info is a little unfriendly user experience.
For example:
1. I can not quickly know wether my app has been supported.
2. I do not know should I use "Photoshop" or "Adobe Photoshop CC 2019" in the config file so that I can sync specified apps.

**Comment by lra** [comment]
No, it's a wish: https://github.com/lra/mackup/issues/604
