### ISSUE TITLE
Globally support XDG_CONFIG_HOME as a preference?

### ISSUE THREAD

**Issue by ionlights** [lra/mackup#1509]
The basic idea is to globally support `$XDG_CONFIG_HOME`. It feels reasonable to naïvely rely on users ensuring it's in their environment.

This feels like it could get gnarly if `mackup` doesn't enforce a prioritization of its own when handling configs that have support like `neovim` does (outlined below).

Consider `neovim` – they support both (with priority, I believe):
- `$XDG_CONFIG_HOME/nvim`
- `$HOME/.nvim`

Personally, I don't see an issue with enforcing a priority of `$XDG_CONFIG_HOME` > `$HOME`, especially since it shouldn't harm anyone who prefers having configs stored in their `$HOME`. 

However, it might be tricky to allow people to toggle support for `$XDG_CONFIG_HOME` on and off since that requires being able to specify both the forward and backward transition (that is, they start out w/ `$HOME`, begin using `$XDG_CONFIG_HOME`, and move back to using `$HOME`).

Another caveat comes up when considering `.gitconfig`, it's normally stored in either:
- `$XDG_CONFIG_HOME/git/config`
- `$HOME/.gitconfig`

I'm not too confident it's easy to specify how to transform filenames if they ever decide to go backand forth, like mentioned before.

**Comment by lra** [comment]
`XDG_CONFIG_HOME` is already supported, see https://github.com/lra/mackup/blob/master/doc/README.md#add-support-for-an-application-using-the-xdg-directory

There are still some app config with hardcoded `.config` and those should be fixed.
TODO added: https://github.com/lra/mackup/issues/1531

**Comment by pikeas** [comment]
What about `.mackup.cfg`? Does Mackup check XDG_CONFIG_HOME for its own config file?

**Comment by lra** [comment]
No, see https://github.com/lra/mackup/issues/1317

**Comment by lra** [comment]
Done in https://github.com/lra/mackup/pull/2113 released in https://github.com/lra/mackup/releases/tag/0.9.3
