### ISSUE TITLE
chattr warning on uninstall and attributes wrong

### ISSUE THREAD

**Issue by halloleo** [lra/mackup#1515]
When I use `mackup uninstall` I get warnings like

```
/usr/bin/chattr: Operation not supported while reading flags on ~/.bashrc
```

Why is that? Also I notice that the attributes of the restored files are not the same as they where before `mackup backup`. :-(

All of this might be related to PR #1040.

**Comment by lra** [comment]
Thanks, fixed in https://github.com/lra/mackup/pull/1040
