### ISSUE TITLE
Any way to backup config files, but prohibit general restore of them?

### ISSUE THREAD

**Issue by halloleo** [lra/mackup#1519]
Firstly, thanks for mackup. It is great! 

From what i see Mackup serves *two* purposes:

1. Syncing settings between machines (via `backup` & `restore` command)

2. Backup settings to a cloud location (via the `backup` command alone).

For some settings I only want to use Mackup for the 2nd purpose: Say i have different proxy settings in `.curlrc` on my two machines I sync via Mackup. I still would like to backup my `.curlrc` file. I can do this easi;y by symlinking them *in the home directory* to `.curlrc_mac1` or `.curlrc_mac2`  respectively, adding these files to `my-files.cfg` and then calling `mackup backup`

But when I restore these files get restored on both machines! This is not what I want because it clutters the home directory.

So, is there any way to backup these files, but prohibit general restore of them?

**Comment by lra** [comment]
You might want to use the custom directory feature, giving each Mackup instance a different directory name to store its files, see https://github.com/lra/mackup/tree/master/doc#custom-directory-name
