### ISSUE TITLE
tunnelblick - config alias  

### ISSUE THREAD

**Issue by Ashtonian** [lra/mackup#1525]
Is there another way mack up could backup Tunnelblick configs? I believe making the configs an alias breaks it. 

https://github.com/Tunnelblick/Tunnelblick/issues/607

**Comment by lra** [comment]
Not sure why Tunnelblick is doing this, but for those, the only solution would be to copy the files instead of linking those, but this is not a simple problem.

Dupe of https://github.com/lra/mackup/issues/613
