### ISSUE TITLE
Support Mac App Store apps

### ISSUE THREAD

**Issue by vitorgalvao** [lra/mackup#154]
Mac App Store apps keep files inside `~/Library/Containers/`. These cannot be replaced with soft links (`ln -s`), but do work with hard links (`ln`) and OS X aliases. Since hard links cannot be used on directories, this would work for many apps, but not all.

My suggestion would be to add `CONTAINERS = 'Library/Containers/'` to `# Commonly used paths #`, and then when *mackup* encounters an app that references something that starts with `CONTAINERS`, use [the applescript way](http://stackoverflow.com/questions/7072208/how-do-i-create-a-macintosh-finder-alias-from-the-command-line/10067437#10067437); else, make a symbolic link as always.

**Comment by dmoutal** [comment]
Also interested in the status of this.

Thanks.

**Comment by lra** [comment]
Well, unless we have a working solution, there is no progress on this.
Anyone has a "working" plan?

**Comment by lra** [comment]
Once https://github.com/lra/mackup/issues/613 is in, it should not be a problem
