### ISSUE TITLE
iStat Menus 6

### ISSUE THREAD

**Issue by LandonSchropp** [lra/mackup#1560]
Mackup currently states that it supports `istat-menus-5`. However, it looks like we're currently on version 6, and the new preferences don't seem to be syncing. Is it possible to update Mackup to support the new version? 

Thanks!

**Comment by jamiew** [comment]
I have been doing this with a custom `~/.mackup/istat-menus-6.cfg` file, and just submitted a PR to combine w/ the current iStat Menus 5 support

**Comment by LandonSchropp** [comment]
Sweet! Thanks @jamiew.

**Comment by lumaxis** [comment]
This was fixed by #1548

**Comment by LandonSchropp** [comment]
Thanks @lumaxis!
