### ISSUE TITLE
Support for Alfred app

### ISSUE THREAD

**Issue by shayonpal** [lra/mackup#1576]
Hi, I don't see any support for Alfred app listed. Is there any scope of supporting Alfred in the future? I would've loved to help myself, if I were a developer 🙂

**Comment by vitorgalvao** [comment]
This has been [rejected multiple times](https://github.com/lra/mackup/search?q=alfred&type=Issues). Syncing settings is part of the paid features of Alfred, so mackup’s author doesn’t want to circumvent that.

**Comment by vitorgalvao** [comment]
#20, #116, #127, #405, #417, #813.

**Comment by jamiew** [comment]
To clarify: as a rule, `mackup` does not add syncing on top of any app that provides its own syncing by default. e.g. Chrome and Alfred (even if paid-only etc)

Would suggest adding as a custom configuration

**Comment by shayonpal** [comment]
> To clarify: as a rule, `mackup` does not add syncing on top of any app that provides its own syncing by default. e.g. Chrome and Alfred (even if paid-only etc)

Can you help me understand how does Alfred provide syncing of settings across devices?

**Comment by vitorgalvao** [comment]
> Can you help me understand how does Alfred provide syncing of settings across devices?

[With a dedicated feature](https://www.alfredapp.com/help/advanced/sync/).
