### ISSUE TITLE
superuser request denied

### ISSUE THREAD

**Issue by suliveevil** [lra/mackup#1582]
I’m using iSH(Alpine Linux Virtual Machine) on iPadOS.
Since it is just a VM  I will not do my work on it, it is just for personal use. It’s not necessary to add a user to this tiny OS.

Would you please let superuser at situation like me using mackup?

**Comment by lra** [comment]
Fixed by https://github.com/lra/mackup/pull/1535
Will be in next version.

**Comment by suliveevil** [comment]
This is awesome!
