### ISSUE TITLE
backup non $HOME based files?

### ISSUE THREAD

**Issue by kurktchiev** [lra/mackup#1583]
So I have a couple of 3rd party binaries that live in /usr/local/bin that I would like to use mackup for, but right now it seems the only workaround not being able to pass in a full path is to make a bin/.bin in $HOME and dump things in there, not huge deal, but it could potentially be useful to be able to grab files in arbitrary locations. I did some searching to see if anyone else had this request and couldn't find anything.

**Comment by lra** [comment]
No. If we allow it, we'll have 10x more issues from people who don't understand how this works.
The point of mackup is to sync user settings (located in the user folder), not system files.

You can have a `~/.local/bin` and sync it using a custom mackup conf, see https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#~/.local/bin/
