### ISSUE TITLE
Mackup app usage

### ISSUE THREAD

**Issue by vegadj** [lra/mackup#1598]
I try to find answer to these questions? I couldn't find any answer? 

1- How to list of apps that is already backed up by mackup in a system?

2- How to list of apps that is supported by mackup but now backed up by mackup yet? (in case of ignore exception or app is newly supported)

3- What to do after new app is installed that is supported for mackup?  

4- What to do if an app is installed and backed on MachineA but not installed on MachineB?

5- In addition to Question 4, what to do if MachineB installs the app after some time ?

**Comment by lra** [comment]
> 1- How to list of apps that is already backed up by mackup in a system?

You can try `mackup -nv backup`

> 2- How to list of apps that is supported by mackup but now backed up by mackup yet? (in case of ignore exception or app is newly supported)

Not sure I understand, but `mackup list`

> 3- What to do after new app is installed that is supported for mackup?

Get a coffee?

> 4- What to do if an app is installed and backed on MachineA but not installed on MachineB?

`mackup restore` on on machineB

> 5- In addition to Question 4, what to do if MachineB installs the app after some time ?

If there is a conflict, it warns you, up to you on how to solve it.
