### ISSUE TITLE
Unsupported absolute path: /etc/dnf

### ISSUE THREAD

**Issue by bdcarr** [lra/mackup#1606]
Context: I'm trying to use mackup to back up my `dnf` config on Fedora, which is located in `/etc/dnf` by default.

I created `~/.mackup/dnf.cfg` with these contents:
```
[application]
name = dnf

[configuration_files]
/etc/dnf
/etc/yum.repos.d

```

When I run `mackup backup` this is the output:
```
Traceback (most recent call last):
  File "/home/bcarr/.local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.29', 'console_scripts', 'mackup')()
  File "/home/bcarr/.local/lib/python3.8/site-packages/mackup/main.py", line 67, in main
    app_db = ApplicationsDatabase()
  File "/home/bcarr/.local/lib/python3.8/site-packages/mackup/appsdb.py", line 52, in __init__
    raise ValueError(
ValueError: Unsupported absolute path: /etc/dnf
```

I assume this is because mackup was originally not meant to be run as root (so dirs like `/etc` wouldn't work), or maybe because entering absolute paths could lead to issues when restoring config on different machines.

However [now there's an option to allow running as root](https://github.com/lra/mackup/pull/1535), and certain applications (such as `dnf`) default their config to `/etc`, so I think there's a use case for allowing absolute paths in certain cases. Maybe require a flag in the application's .cfg file so the user has to make explicit that they really meant to use an absolute path?

Unless there's another reason for disallowing those paths that I haven't thought of (likely)?

Anyway, for the moment I'll see about moving dnf's config dir to `~/.config` or something. Of course that'll be an extra step needed when restoring on a different machine, so you can see why I've opened this issue.

edit: looks like it's not actually possible to move the `dnf` config folder :disappointed:

**Comment by lra** [comment]
Mackup is supposed to sync user files across different computers. Allowing non user files to sync will lead into a lot of system specific program to badly sync across computers. This will lead to more misunderstanding than anything.

https://github.com/lra/mackup/issues/779
https://github.com/lra/mackup/issues/918

If you really want to do this, you might want to link the dnf conf into your home dir and sync it with mackup. Or ask upstream for the program to support user's config file but I doubt they will do it for the same reason.
To backup your system you might want to take a look at a backup software.

**Comment by bdcarr** [comment]
Fair enough, thanks for replying mate.

**Comment by bdcarr** [comment]
Just in case anyone else is trying to do the same thing as me without using full-on backup software, I worked around it with the following. Bonus bit in there for backing up the list of installed vscode extensions, which has to be dumped each time:

1. Create a function `mackupbackup`:
```
echo 'Copying dnf config to ~/.config/etc/';
cp -r /etc/{dnf,yum.repos.d} ~/.config/etc;
echo 'Saving Visual Studio Code extensions list to ~/.config/vscode_extensions_list.txt';
code --list-extensions > ~/.config/vscode_extensions_list.txt;
echo 'Running mackup backup...';
mackup backup -f;
echo 'Done!';
```
2. Create config files in `~/.mackup` to back up the files placed in `~/.config` by the above function
3. Use `mackupbackup` every now and then
