### ISSUE TITLE
uninstall Mackup, Apple Music still write plist file into iCloud

### ISSUE THREAD

**Issue by viewv** [lra/mackup#1607]
OS: macOS 11 beta
First I run `mackup uninstall` and then I run `brew uninstall mackup`, but I find that Apple Music is still write com.apple.Music.plist file to iCloud ( I use iCloud as backup place ).

I check the Preferences path:
<img width="657" alt="Screen Shot 2020-07-25 at 17 52 48" src="https://user-images.githubusercontent.com/32566594/88454125-aa451f00-ce9f-11ea-8912-024a89425313.png">
Really confusing.

**Comment by lra** [comment]
1. Reinstall mackup
1. enable back apple music, 
1. mackup backup
1. mackup uninstall
1. uninstall mackup

**Comment by viewv** [comment]
> * Reinstall mackup
> * enable back apple music
> * `mackup backup`
> * `mackup uninstall`
> * uninstall mackup

Thank you, I tried, but still that same problem, I even tried backup into a local folder, and its back up to my local folder, but still sync to iCloud.

**Comment by viewv** [comment]
OK, after I reboot my Mac, this problem seems fixed, thx.
