### ISSUE TITLE
Is it possible to have multiple storage locations?

### ISSUE THREAD

**Issue by dustinknopoff** [lra/mackup#1624]

**Comment by lra** [comment]
No.

**Comment by tpvasconcelos** [comment]
Is it in the roadmap? 

One use case I have to is sharing some dotfiles in a public repository while keeping other preferences and settings files in a private storage location.

**Comment by tpvasconcelos** [comment]
@lra this be achieved by adding a flag to the CLI for specifying the path to the config file. It would default to `~/.mackup.cfg` ofc, but you could also pass `--config=~/.mackup.public.cfg`,  `--config=~/.mackup.private.cfg`, `--config=~/.yet_another_one.cfg`, etc...
