### ISSUE TITLE
Unsupported application: Homebrew

### ISSUE THREAD

**Issue by maboloshi** [lra/mackup#1643]
```
  mackup show Homebrew
Unsupported application: Homebrew
```
The built-in configuration file exists [homebrew.cfg](https://github.com/lra/mackup/blob/master/mackup/applications/homebrew.cfg)

**Comment by Gladkov-Art** [comment]
It seems that it hasn't been released yet.

**Comment by maboloshi** [comment]
I see. I didn't notice it before. Thanks for the reminder.
