### ISSUE TITLE
Pypoetry: update config.cfg -> config.toml

### ISSUE THREAD

**Issue by pikeas** [lra/mackup#1647]
https://github.com/lra/mackup/blob/master/mackup/applications/poetry.cfg

https://python-poetry.org/docs/configuration/

**Comment by ameyuuno** [comment]
Hi! I made [PR](https://github.com/lra/mackup/pull/1632) to fix it on September 20 but it is still not merged ¯\_(ツ)_/¯

**Comment by lra** [comment]
Fixed by https://github.com/lra/mackup/pull/1632
