### ISSUE TITLE
Brave listed in supported applications but not supported in latest release

### ISSUE THREAD

**Issue by piersolenski** [lra/mackup#1648]
Brave Browser is listed in the supported applications but doesn't seem to actually be supported in version 0.8.2 https://github.com/lra/mackup/tree/0.8.29/mackup/applications

**Comment by lra** [comment]
That's because https://github.com/lra/mackup/blob/master/README.md is following master, not a specific version.
The README of 0.8.29 did not list Brave: https://github.com/lra/mackup/blob/0.8.29/README.md

This is now fixed as the latest releases include Brave.

**Comment by piersolenski** [comment]
Awesome! 🙏
