### ISSUE TITLE
restore using iCloud does not restore all files

### ISSUE THREAD

**Issue by cyberjar09** [lra/mackup#1649]
Hi im using MacOS 10.15.7 on both the old laptop and new one
im using iCloud as my backend for syncing (simply because its easiest to bootstrap without having to log into another cloud account, the config is easy to bootstrap mackup)
when I did a `mackup restore` on the new machine I noticed the majority of the files were back as expected. One app I expected the config to appear was hammerspoon

Here is what the folder structure for hammerspoon in my old laptop looks like
```
tree -a ~/.hammerspoon
/Users/rudy/.hammerspoon
├── Spoons
│   ├── ClipboardTool.spoon
│   │   ├── docs.json
│   │   └── init.lua
│   ├── MiroWindowsManager.spoon
│   │   ├── docs.json
│   │   └── init.lua
│   └── miro-windows-manager-1.1
│       ├── MiroWindowsManager.spoon
│       │   ├── docs.json
│       │   └── init.lua
│       ├── MiroWindowsManager.spoon.zip
│       └── README.md
├── init.lua
└── misc
    └── clipboard.lua
```

here is what I see on the mew laptop
```
tree -a /Users/rudy/Library/Mobile\ Documents/com\~apple\~CloudDocs/Mackup/.hammerspoon
/Users/rudy/Library/Mobile\ Documents/com~apple~CloudDocs/Mackup/.hammerspoon
├── .init.lua.icloud
├── Spoons
│   ├── .ClipboardTool.spoon.icloud
│   ├── .MiroWindowsManager.spoon.icloud
│   └── miro-windows-manager-1.1
│       ├── .MiroWindowsManager.spoon.icloud
│       ├── .MiroWindowsManager.spoon.zip.icloud
│       └── .README.md.icloud
└── misc
    └── .clipboard.lua.icloud
```

when I look into the files, they are still encrypted  

questions? thoughts? ideas? suggestions?
thanks

**Comment by derylseale** [comment]
I ran into something similar, and I fixed it by ensuring the iCloud drive was fully synced on my computer. It looks like using mackup will force a sync with individual files, but directories are just linked, and that does not force a sync. If you click the little cloud icon next to the Mackup directory in Finder, it should sync all the underlying files and then you'll be fine.

**Comment by JasonMFry** [comment]
fwiw I was having the same problem, `mackup backup` on my old machine results in iCloud trying to sync over 35,000 files, over 800MB of data. I needed to wait until iCloud uploaded everything and the new machine downloaded it, _then_ I can do `mackup restore`
