### ISSUE TITLE
p10k missing in applications

### ISSUE THREAD

**Issue by IvanIFChen** [lra/mackup#1659]
While using the latest version of mackup 0.8.29_1 distributed by brew, it looks like application `p10k.cfg` is missing in `applications`. 

I am looking at `Cellar/mackup/0.8.29_1/libexec/lib/python3.9/site-packages/mackup/applications` and I was not able to find `p10k.cfg` but was last updated on the repo about 2 months ago.

Thanks.

**Comment by lra** [comment]
WFM:
```
lolo@mbp ~> ls -l /usr/local/Cellar/mackup/0.8.31/libexec/lib/python3.9/site-packages/mackup/applications/p10k.cfg 
-rw-r--r--  1 lolo  staff  59 Jan  3 21:22 /usr/local/Cellar/mackup/0.8.31/libexec/lib/python3.9/site-packages/mackup/applications/p10k.cfg
```

Open this again if you still have the issue.
