### ISSUE TITLE
Question about adding a new application to backup

### ISSUE THREAD

**Issue by zirawell** [lra/mackup#1668]
I have already run the code 'Mackup backup' now.  I have backed up all my app config now. 
But if I want to backup my app configs again when I download a new application, what should I do?
I have read about how backup works, it will move my configs to the backup places and create alias at the original places to the backups. I have tried cp the alias to the backup and it failed. 
Is it true that it will only backup the config of application which has not been backed up and has no effect to the configs of those which have been backed up when I run the code 'Mackup backup'  twice?

**Comment by joshmedeski** [comment]
You should be able to run mackup backup again :)

Please share more details with us if that doesn't work for you.

**Comment by zirawell** [comment]
> You should be able to run `mackup backup` again :)
> 
> Please share more details with us if that doesn't work for you.

Ok, thanks for reply. I will have a try.

**Comment by lra** [comment]
Yes `mackup backup` should be idempotent (running it again should be harmless).
Ideally, you want to run `mackup backup` each time you install a new application, so it syncs the config of the new application only.
