### ISSUE TITLE
Application names with space are not getting ignored

### ISSUE THREAD

**Issue by jasmeet2dhiman** [lra/mackup#1670]
My .mackup.cfg is below ignored applications but mackup is still doing the backup for both.

[applications_to_ignore]
Adobe Camera Raw
WhatsApp Web

**Comment by joshmedeski** [comment]
@jasmeet2dhiman Please try using the name of the files without the `.cfg` extension like so:

```
[applications_to_ignore]
adobe-camera-raw
whatsapp
```

@lra would it be good to update the [documentation](https://github.com/lra/mackup/blob/master/doc/README.md#dont-sync-an-application) to be more clear on what name is used in the config file?
