### ISSUE TITLE
Simulation mode

### ISSUE THREAD

**Issue by BajaCali** [lra/mackup#1673]
Hi guys, this is a feature request for a mode of restoring data but only as a **simulation**. It means that mockup just tells me what it will do, but does not change anything. Just like `-n, --no, --simulate` params works on [`stow`](https://dart.dev/guides/testing). I have to request it because this feature could have saved some of my data.

**Comment by BajaCali** [comment]
Ok, just learnt that it already does exists.

**Comment by lra** [comment]
FTR: `-n --dry-run  Show steps without executing.`
