### ISSUE TITLE
How can I sync 2 machines (same OS) but different folders (e.g. anaconda vs miniconda)?

### ISSUE THREAD

**Issue by MR-T77** [lra/mackup#1680]
Hi!

I've been using mackup to sync my settings between 2 Macos, but I'm having issues with conda, since in one machine I have anaconda and in the other I have miniconda.
So, whenever I sync, one of the machines stops working.
How can I prevent this?

**Comment by lra** [comment]
Don't sync them: https://github.com/lra/mackup/tree/master/doc#dont-sync-an-application
