### ISSUE TITLE
Mackup keeps syncing ~/.zshrc although I have zsh in [applications_to_ignore] in ~/.mackup.cfg

### ISSUE THREAD

**Issue by MR-T77** [lra/mackup#1686]
I'm using Mackup to sync 3 machines, but I can't find a way not to sync zsh, as I need specific .zshrc files per machine.
I have a ~/.mackup.cfg in all machines where zsh is under [applications_to_ignore]. (My [applications_to_sync] is empty).
What am I doing wrong or how may I tell mackup not to sync ~/.zshrc files?

**Comment by ionlights** [comment]
Just checking – have you removed the symlink from your `~/.zshrc -> /path/to/mackup/.zshrc`?

**Comment by MR-T77** [comment]
No, I didn't. Should I?
