### ISSUE TITLE
Add Obsidian

### ISSUE THREAD

**Issue by xplosionmind** [lra/mackup#1719]
It would be great if Mackup could sync [Obsidian](https://obsidian.md "Obsidian") vaults settings, too.

A problem may be that Obsidian configuration files have no standard location: the are placed in a sub-folder of the vault, called `.obsidian`. Nevertheless, if the path to the vault is specified, it is super easy and useful.

**Comment by joshmedeski** [comment]
Feel free to make a PR, here are instructions for [how to contribute](https://github.com/lra/mackup/blob/master/.github/CONTRIBUTING.md).

**Comment by xplosionmind** [comment]
Unfortunately, I do not have enough technical skills to do this, but I hope someone will.

Thank you very much anyways!

**Comment by joshmedeski** [comment]
See https://github.com/lra/mackup/tree/master/doc#add-support-for-an-application-or-any-file-or-directory

You can create a file named `~/.mackup/obsidian.cfg`. This would be content:
```
[application]
name = obsidian

[configuration_files]
vault-path/.obsidian
```

You'll have to replace `vault-path` with the path to your Obsidian vault. It might take some experimenting to get it right but hope this helps.

**Comment by Amparose** [comment]
I don't think this is necessary as each Obsidian vault is a self-contained bundle of app data (the note files) and app settings (themes and plugins). So if you are syncing your vault to get your notes across devices, there's no need/point in hooking up Mackup to sync settings.

**Comment by xplosionmind** [comment]
> I don't think this is necessary as each Obsidian vault is a self-contained bundle of app data

You’re right. If someone really needs to use mackup, they can do so by adding the config themselves, as @joshmedeski kindly suggested.
