### ISSUE TITLE
Can't mackup or uninstall

### ISSUE THREAD

**Issue by Palvehelmed** [lra/mackup#1721]
Hi,
I meet a problem. Whichever command I use, it just show like this:

```
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.32', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/main.py", line 67, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/appsdb.py", line 44, in __init__
    app_pretty_name = config.get("application", "name")
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'application'
```

I have tried to use `brew uninstall` or `brew reinstall`, it doesn't work.
Please help me to make it normal to use, Thanks u :D

**Comment by joshmedeski** [comment]
Can you please show us your `~/.mackup.cfg` file? You may have a syntax error or have misconfigured mackup in some way.

**Comment by Palvehelmed** [comment]
Appreciate for your reply.

My `~/.mackup.cfg` is as follows.

```
[applications_to_ignore]
quicklook

[storage]
engine = dropbox
directory = .config/mackup
```
I don't see anything wrong. It was worked when I installed it. And I don't know when it doesn't work or I misconfigured it.

**Comment by joshmedeski** [comment]
> With the dropbox storage engine, Mackup will automatically figure out your Dropbox folder.
https://github.com/lra/mackup/tree/master/doc#add-support-for-an-application-or-any-file-or-directory

You can't specify the directory if you're using the dropbox engine. You can switch to the `file_system` engine if you're trying to use Mackup from a specific directory.

Here's how you'd sync the directory you chose:
```
[storage]
engine = file_system
path = .config
directory = mackup
```

**Comment by Palvehelmed** [comment]
Thank you a lot for the help.
That is the correct reason I can't make it work. When I reconifgure the .cfg file and move the .conifg Folder back to home, it works.

**Comment by joshmedeski** [comment]
You're welcome, glad we figured it out :smile:
