### ISSUE TITLE
Issue on M1 Mac

### ISSUE THREAD

**Issue by adibhanna** [lra/mackup#1723]
I'm unable to install `mackup` on my M1 Mac with just `brew install mackup`, I need to do `arch -arm64 brew install mackup`
When I do so, it installs, but when I try to run it, i'm getting this: 

```
▶ mackup
[1]    9584 killed     mackup
```

Any idea how I can fix this? 
THANK YOU

**Comment by joshmedeski** [comment]
Mackup has been working fine for me after install with `arch -arm64 brew install mackup` on my m1.

Try uninstalling it and reinstalling it. If the console can give you more feedback that will help us troubleshoot.

**Comment by adibhanna** [comment]
I uninstalled it and installed it again, and here's what I'm getting

```
▶ arch -arm64 brew install mackup
==> Downloading https://homebrew.bintray.com/bottles/mackup-0.8.32.arm64_big_sur.bottle.tar.gz
Already downloaded: /Users/adibhanna/Library/Caches/Homebrew/downloads/08c24b5047ab7bd82846806270639f58c606b5d29afeac0ac7a1c64422e7a737--mackup-0.8.32.arm64_big_sur.bottle.tar.gz
==> Pouring mackup-0.8.32.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/mackup/0.8.32: 1,122 files, 7.3MB

~
▶ mackup
[1]    98992 killed     mackup
```

Still same issue

**Comment by joshmedeski** [comment]
Hmm, that's strange. I'm not what could be causing this problem since it just states a killed task.

Maybe @lra can shed some light? Maybe python3 needs to be installed?

**Comment by adibhanna** [comment]
I do have python 3.9.2 installed

**Comment by joshmedeski** [comment]
There's no enough output for me to know where to start debugging. Perhaps @lra has a clue as to why the process is immediately killed.

**Comment by adibhanna** [comment]
My issue was with sqlite not being installed correctly, when I fixed it, everything worked perfectly! 

Thank you for taking the time to look into this! 
We can close this issue now.
