### ISSUE TITLE
French spacing

### ISSUE THREAD

**Issue by LucasLarson** [lra/mackup#1727]
It looks like some of this was built by a français with French spacing` `? We should remove the spaces between sentences and their question marks and exclamation points like this:
```diff
-Are you sure that you want to replace it ?
+Are you sure that you want to replace it?
```
Example taken from: https://github.com/lra/mackup/blob/9f275ed1589c55273eac4a71ff3bf8c480860c15/mackup/application.py#L104-L105

**Comment by lra** [comment]
You are right 🇫🇷

**Comment by LucasLarson** [comment]
resolved in https://github.com/lra/mackup/commit/442a4add4c9955c713655cc2520a876b5ac7a385
