### ISSUE TITLE
mackup restore on new machine cause PermissionError: [Errno 13] Permission denied: 'Contents'

### ISSUE THREAD

**Issue by uni-pai** [lra/mackup#1751]
Hi, I am having a problem using mackup with file_system. what I do is the following
PermissionError: [Errno 13] Permission denied: 'Contents'

**Comment by joshmedeski** [comment]
Please share the contents of your `~/.mackup.cfg`, maybe there's an issue with the configuration.

**Comment by uni-pai** [comment]
> Please share the contents of your `~/.mackup.cfg`, maybe there's an issue with the configuration.

```
[storage]
engine = file_system
path = /Users/aiden/Nutstore Files/.symlinks/坚果云
directory = Mackup
```

**Comment by joshmedeski** [comment]
Your `path` needs to be relative to the home directory. Change it to this:

```
[storage]
engine = file_system
path = Nutstore Files/.symlinks/坚果云
directory = Mackup
```

See [Configuration - File Storage](https://github.com/lra/mackup/blob/master/doc/README.md#file-system) for more info.
