### ISSUE TITLE
How to switch from iCloud to sync.com?

### ISSUE THREAD

**Issue by JasonMFry** [lra/mackup#1760]
I know there's no official support for sync.com, but it creates a directory (usually `~/Sync` but it can be configured), and anything in that directory gets synced. I currently use iCloud and want to experiment switching to sync.com, but I'm concerned that experimenting will result in me deleting things. What do I need to do to experiment with this switch without losing data? The following steps is what I plan, but will this work?

1. Update ~/.mackup.cfg
    ```
    [storage]
    engine = file_system
    path = Sync
    ```
1. $ `mkdir ~/Sync/Mackup`
1. $ `mackup backup`

**Comment by lra** [comment]
That would work, until it's officially supported. But make sure sync.com supports symlinks, some sync providers replace those with files or don't sync those.

**Comment by JasonMFry** [comment]
> That would work

Would I lose any data if I did what I outlined above? In other words, does Mackup remove files from iCloud in this situation?

> until it's officially supported

If you point me in the direction, I might be able to add that

> But make sure sync.com supports symlinks

Here's what sync.com's [help article](https://www.sync.com/help/how-do-i-sync-folders-outside-of-the-sync-folder-on-windows/) says, seemingly relevant things in **bold**

> Note: **Symbolic links are not officially supported.** This article provides directions as a reference ...

> Symbolic Links are synced to the cloud in intervals of 20 minutes as long as no other processes are taking place in Sync.

> **You will not be able to symlink to your Documents folder directly as Windows has symlinks in it already to other folders such as the Music folder.** If you want to symlink to your Music, Videos or Pictures folders you’ll need to link to the original folder outside of Documents.

This indicates that it's not supported, but it works? But not with nested symlinks? What is your take on this?

**Comment by JasonMFry** [comment]
fwiw, as a test I made a symlink of my `~/.config` and put that symlink in `~/Sync`. Notably, `~/.config` contains a symlink to `nvim/`. But I can go to sync.com's web app and see everything in `~/.config`, even the symlinks, and can even download them. So that indicates to me it works.

**Comment by lra** [comment]
> Would I lose any data if I did what I outlined above? 

Can't tell, depends on the sync provider implementation, some are really stupid.

> If you point me in the direction, I might be able to add that

https://github.com/lra/mackup/blob/master/mackup/utils.py#L196
The point is to find out how to get the sync provider path.

> This indicates that it's not supported, but it works? But not with nested symlinks? What is your take on this?

If it's not supported, I would not support this officially, because people tend to blame the last element in the chain for losing their file, and Mackup is usually it.

You can still use it with your `file_system` config.

**Comment by JasonMFry** [comment]
Adding this here for anyone who happens upon this issue looking for answers. I've been using mackup in Sync.com for since Sept 13, 2021, and have had no problems. I'll try to remember to update this comment if that changes, but no promise.
