### ISSUE TITLE
Entry at the top of the README that explains THIS TOOL CAN BE DANGEROUS!!!!

### ISSUE THREAD

**Issue by JaredVogt** [lra/mackup#1775]
There should be a HUGE warning at the top that this tool moves all files to the mackup directory and then links back. I assumed (and there is nothing with GIANT LETTERS THAT SAYS otherwise) that this backed up files.. IOW, made a copy of them. I deleted the mackup directory that was created before I figured this out. I was just exploring the tool... to see what it would do. I deleted the folder because I wanted to move it to a different location - and I did it almost immediately after running. Thank god, it appears that all of the files where synced to Dropbox so I could grab a backup from there. But.. if there are any files missing, how would I know?? Regardless.. I spent 15mins with my mind utterly blown thinking I had just blown away all of the config on my machine. I only noticed it when I opened a shell and it choked... then I ls'ed my home dir and saw all the links. OMG, please, make sure you let people know what/how this tool works.

**Comment by lra** [comment]
It's already [clearly explained](https://github.com/lra/mackup/blob/master/README.md#what-does-it-do), writing everything in giant red letters won't stop stupid people who assume to do stupid things.

If you don't check the README of a tool, and the warnings of a tool (it keeps asking you to confirm) before you run it on your computer, the problem might not be the tool.

**Comment by JaredVogt** [comment]
That actually made me laugh out loud... hey, why mince words. Two things. One, I used mackup the first time a year or two ago - and I don't think the behavior was the same? It previously just did the `cp` without the `rm` - didn't it? Second... you use the word "backup" - which has meaning and connotation that just seems different. You are centralizing all of the config files - and the backup is just an artifact of where you happen to place it (eg Dropbox). Whatever... take the suggestion, or call it stupid - don't care. 
I do wish you had a version that would simply just do the `cp` portion. Yesterday I was just trying to see how various apps store their data.

**Comment by lra** [comment]
> One, I used mackup the first time a year or two ago - and I don't think the behavior was the same?

It's always been, you are assuming again, it's all in git if you want to check.

> I do wish you had a version that would simply just do the cp portion.

https://github.com/lra/mackup/issues/613
