### ISSUE TITLE
.gitignore_global isn't backed up

### ISSUE THREAD

**Issue by evanharmon1** [lra/mackup#1783]
Is the intention to add `.gitignore_global` manually via mackup configuration? Or is it intended to backup this file by default? It is not backing up for me.

I'm on MacOS Monterey 12.01, MacBook Pro 2021, Apple M1 Max

**Comment by lra** [comment]
Yes, it's not an official file. It's just an example in the documentation. You can add it yourself to a custom config: https://github.com/lra/mackup/blob/master/doc/README.md#add-support-for-an-application-using-the-xdg-directory

**Comment by evanharmon1** [comment]
Gotcha. Makes sense. I thought .gitignore_global was more of an officially set file. I'll add it manually. Thanks.
