### ISSUE TITLE
macOS Monterey support with Apple M1?

### ISSUE THREAD

**Issue by dzogrim** [lra/mackup#1794]
Hi!

Is there any known issues with Monterey? Or Silicon?
I did not have problems before and now I have the impossibility to have sync with 

- Bartender
- iTerm 2
- Viscosity
- even Xcode

and some other apps on Dropbox.
Actually, it seems that something is blocking apps to read/follow symbolic links that are created…
Apps are launching as the first time each time I start it (Welcome screen, no more licence, etc.).
But it seems OK for some other apps… So I granted _full disk access_ but it **doesn't** resolve that.
So for now I add to add those apps to ```[applications_to_ignore]``` 😢 

I'm running macOS Monterey 12.1 (21C52) on MacBook Pro 13-inch, M1 (2020)

Regards,

Sébastien L.

**Comment by lra** [comment]
It might be problems with the applications themselves, I'm on an M1 Monterey and have no issue with the apps I'm using.

Maybe those applications use a different path per architecture?

**Comment by dzogrim** [comment]
Yeah! you're probably right @lra ; thanks for your answer!
With my second MacBook Pro Intel, I don't have any troubles either … and this is my first M1 architecture computer. I just wonder what could be wrong with that links on those programs. Could you give a try with iTerm 2 since it's free please?
I wish I was not the only one to encounter this problem and find out a workaround.
Sorry~
Thx

**Comment by lra** [comment]
look at the iterms2 file (see https://github.com/lra/mackup/blob/master/mackup/applications/iterm2.cfg) on each architecture, maybe some apps store arch specific config, and reset those if found on another arch?

Can't really test every application out there, sorry.

**Comment by dzogrim** [comment]
> look at the iterms2 file (see https://github.com/lra/mackup/blob/master/mackup/applications/iterm2.cfg) on each architecture, maybe some apps store arch specific config, and reset those if found on another arch?
> 

This is the good place (path) and the good file name. This is actually used by the app currently. 
Thanks anyway

**Comment by theMajc** [comment]
Having exact same issue here on OSX 12.1 / 14-inch 2021 M1 Pro.

```sh
# before backup
ls ~/Library/Preferences/com.googlecode.iterm2.plist
-rw-------   209K ~/Library/Preferences/com.googlecode.iterm2.plist

mackup show iterm2
Name: iTerm2
Configuration files:
 - Library/Preferences/com.googlecode.iterm2.plist

# after backup
ls ~/Library/Preferences/com.googlecode.iterm2.plist
lrwxr-xr-x    93B ~/Library/Preferences/com.googlecode.iterm2.plist@ -> ~/Mackup/Library/Preferences/com.googlecode.iterm2.plist
```
