### ISSUE TITLE
Emacs.d folder still backed up even though Emacs application is added to the ignore list

### ISSUE THREAD

**Issue by shivams** [lra/mackup#1831]
I have added "emacs" to my ignore list by adding the following to my `mackup.cfg` file:

```
[applications_to_ignore]
vim #For I am using SpaceVim
emacs #For I am using Doom Emacs
```

And yet, the `emacs.d` folder is synchronized. Is this a bug or am I doing something wrong?

**Comment by joshmedeski** [comment]
Can we see all of your `mackup.cfg` file? You'll also want to make sure it's located at the home directory and include a `.` at the beginning of the file before running any mackup commands (i.e. `~/.mackup.cfg`)

**Comment by joshmedeski** [comment]
Okay, thanks. Is it ignoring `vim`? 

Perhaps it's detecting [doom-emacs](https://github.com/lra/mackup/blob/master/mackup/applications/doom-emacs.cfg), try adding that to your `applications_to_ignore`.

Also, try removing the inline `#` comments. We may not support that (I haven't seen the source code).

**Comment by shivams** [comment]
Thank you guys for your prompt responses. Turns out the inline `#` comments were causing the issue. It was also backing up the `.vim` folder but since it was softlinked to ` .SpaceVim` folder, I wasn't aware of it. So, having those inline comments effectively made those lines useless. I first uninstalled the mackup (`mackup uninstall`, then removed those inline comments, and then did the backup again (`mackup backup`). And voila! `emacs.d` folder was not backed up anymore.

**Comment by shivams** [comment]
I think `mackup` should show some warning if it's not able to parse some of the configuration properly. In this case, it should have issued me some warning that it can't recognize the applications that it is supposed to ignore as per the config file.

If you feel, this issue can be re-opened or a new issue created based on this feature request that _mackup should show warning in case of faults in the config_

**Comment by joshmedeski** [comment]
Thanks for the feedback. I've added a new issue to add support for inline comments in the config file.
