### ISSUE TITLE
Espanso config files not resolving correctly

### ISSUE THREAD

**Issue by jgoodrick** [lra/mackup#1845]
I tried to reason through the codebase to figure out what is going wrong, but I have a hard enough time reading python, let alone debugging it. However, when I run 'mackup backup' for the first time, I never get the 'espanso' folder from the user folder (should be: Library/Application Support/espanso). When I run 'mackup show espanso' I get the following output:

```
➜  ~ mackup show espanso
Name: espanso
Configuration files:
 - Library/Preferences/espanso
 - .config/espanso
```

which is obviously not right. I even went and checked the file in this repo under 'mackup/mackup/applications/espanso.cfg and this is what we see:

```
[application]
name = espanso

[configuration_files]
Library/Application Support/espanso

[xdg_configuration_files]
espanso
```

so the .config/espanso makes sense, since it resolves from the xdc_configuration_files, but the Library/Preferences/espanso is just wrong, and I have no idea why it would be. It should resolve to Application Support, not Preferences, right?

**Comment by joshmedeski** [comment]
Can you tell us which version of mackup you are running? (run `mackup --version`)

And, do you have any custom config files (`~/.mackup/*.cfg`). I want to make sure there are no overwrites changing the behavior.

**Comment by joshmedeski** [comment]
@lra I'm getting the same thing when I run that command (I'm on `Mackup 0.8.34` and don't have a custom config).

```
$ mackup show espanso
Name: espanso
Configuration files:
 - Library/Preferences/espanso
 - .config/espanso
```

It appears something is going wrong, haven't figured out the root cause yet. Any ideas?

**Comment by jgoodrick** [comment]
Yes, sorry, I am running 0.8.34 as well, and I did not have a custom config before writing this, however, I found that adding one for espanso did work as expected, and allowed me to override the incorrect behavior.

**Comment by joshmedeski** [comment]
I figured it out. https://github.com/lra/mackup/pull/1841 changed the config but my guess is it isn't released yet.

**Comment by joshmedeski** [comment]
@lra it might be good to keep the previous value as a backup for anyone on older versions of Espanso.

> NOTE: when migrating from the previous 0.7.3 version, the configuration directory will be located in $HOME/Library/Preferences/espanso for compatibility purposes.

**Comment by lra** [comment]
Mmmh nice find, someone up for a PR to add both the old and new path in the app config?

**Comment by joshmedeski** [comment]
I'll do it now @lra

**Comment by jgoodrick** [comment]
Thanks, I just came back to check on this, and it looks like you've already submitted the PR. So does espanso remember where it took a file from originally, in order to put it back during espanso uninstall? I just wasn't sure that you could put multiple paths in the cfg file and have it know where to put things back during uninstall.
