### ISSUE TITLE
How to chose a Dropbox instance/directory (when using 2+ Dropbox accounts at the time)

### ISSUE THREAD

**Issue by lptn** [lra/mackup#1852]
I'm using 2 Dropbox account: corporate and private. Mackup uses corporate one for backups, what is not what I want. How can I configure Mackup to use private account?

**UPD**:
the solution can be
```ini
[storage]
engine = file_system
path = ~/cloud/Dropbox (Personal)
```

but I believe there is should be a better one

**Comment by joshmedeski** [comment]
This will work! I can't think of a better way since you've got multiple Dropbox folders on your machine.
