### ISSUE TITLE
Questions about usage after setting up

### ISSUE THREAD

**Issue by gridsystem** [lra/mackup#1860]
Mackup looks great, I've been reading through docs and have setup a config file on one machine, added some ignores to it and backed up a bunch of stuff to icloud.

I've run a dry run of `mackup restore` on the newer machine. Before I do restore from the backup, I just want to make sure I've understood everything correctly before make any assumptions and risk losing any data!

After I have done the initial backup on old machine and restore on new, can I also run `mackup backup` on new, to backup files which were not present on old machine? I'm not talking about merging two bash configs together, I mean backup bash on old machine and backup curl on new machine, then end up with bash and curl configs on both machines.

After I have done the initial backup and restore, can I safely continue to run `mackup backup` and `mackup restore` from time to time on *both machines*, to add newly generated configs which either of them created?

Thanks so much in advance for helping me :)

**Comment by joshmedeski** [comment]
Great, I'm glad you found the related issues that have already been covered. Looking forward to seeing your upcoming PRs.
