### ISSUE TITLE
Mavericks caching issue renders mackup useless and harmful with some apps

### ISSUE THREAD

**Issue by inonprince** [lra/mackup#194]
Mavericks uses cfprefsd deamon to cache app settings. This caused mackup not to work for many apps (for example Forklift, F.lux) and even worse, to delete settings.

http://www.macinside.info/process.php?id=6616

Steps to reproduce:
1. Login in both computers
2. Open Forklift (for example, can be any app with a plist file in ~/Library/Preferences/) in both computers.
3. Quit Forklift in both computers.
3. On computer #1, change a setting for the app, close the app, and wait for dropbox to sync the file to the second computer.
4. On computer #2, open forklift. You will notice the app doesn't reflect your change.
5. Close the app. The plist file will get overwritten with the settings that are on computer #2, therefore deleting the setting you've set on step 3.

I've tried disabling the cfprefsd service, however, this prevents the mac from loading any plist file.

**Comment by lra** [comment]
Centralized in https://github.com/lra/mackup/issues/615
