### ISSUE TITLE
BE ALERT TO DATA LOSS!!!!!!

### ISSUE THREAD

**Issue by Angboo** [lra/mackup#1944]
This problem also occurred to me. At the same time, I found that a large number of configurations became soft links but did not exist in the backup folder, resulting in the loss of a large number of application configurations, such as git's .gitconfig and asdf's .toolversion.

At present, it seems that for the backup function, modifying the user's original configuration is not a good idea. When a program error occurs, the original configuration will be lost. This is extremely fatal for both backup software and users.

**Comment by lra** [comment]
This is too vague for a bug report. Mackup does not store files, it moves them where you told it to. This is all explained.
