### ISSUE TITLE
Config Parser deprecated issue

### ISSUE THREAD

**Issue by koconder** [lra/mackup#1948]
``` ~ % mackup restore -f 
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/main.py", line 66, in main
    mckp = Mackup()
           ^^^^^^^^
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/mackup.py", line 24, in __init__
    self._config = config.Config()
                   ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/config.py", line 46, in __init__
    self._parser = self._setup_parser(filename)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/config.py", line 150, in _setup_parser
    parser = configparser.SafeConfigParser(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

**Comment by MrZoidberg** [comment]
Is there a workaround?

**Comment by koconder** [comment]
@MrZoidberg already raised a PR #1949 and tested the changes locally and its working without issues in my current deployment

**Comment by castus** [comment]
Hi @lra , when do you plan to release this?

**Comment by lra** [comment]
Done: https://github.com/lra/mackup/releases/tag/0.8.39

**Comment by castus** [comment]
Thanks. Could you please update brew formula https://github.com/Homebrew/homebrew-core/blob/master/Formula/m/mackup.rb also?

**Comment by lra** [comment]
I don't maintain this, anyone can.

**Comment by castus** [comment]
So what file do you maintain to have `mackup` up to date with `brew`?

**Comment by psarossy** [comment]
@castus The homebrew formula picks the updates up automatically (already on 0.8.39 there as well).

**Comment by lra** [comment]
Not automatically, someone did: https://github.com/Homebrew/homebrew-core/pull/153351

**Comment by psarossy** [comment]
@lra apologies, you are correct, mackup indeed doesn't have github actions enabled after all... so the update is automated but someone has to trigger the PR manually...

**Comment by frederikkempe** [comment]
Thanks @lra! Works like a charm.
