### ISSUE TITLE
Backup Only Mode

### ISSUE THREAD

**Issue by ahmadawais** [lra/mackup#1964]
This is an amazing piece of software. Sadly, I have had so many issues over the last year or so that my entire config is a mess now. Everytime I restart — all or some configs are lost. 

It's been discussed in so many issues like #1925 #1916 

I'm requesting a backup only mode. Which would work like this:

1. Backup all config in Dropbox
2. No symlinks (let the files stay where they are)
3. Run on a schedule — like backup once every day

This would be enough for so many folks. Thanks so much for considering this.

**Comment by lra** [comment]
This is now planned, started a discussion about it: https://github.com/lra/mackup/discussions/1969
