### ISSUE TITLE
Mackup breaks Raycast

### ISSUE THREAD

**Issue by Stono** [lra/mackup#1980]
Hi, 
I'd been debugging a problem with Raycast configuration not surviving reboots.

It turns out it is this: https://github.com/lra/mackup/pull/1664#issuecomment-1013563133

Raycast + Mackup don't work together; so my feeling is the config should be removed as others will undoubtably feel this pain!

One of the maintainers of Raycast also confirmed this incompatibility on slack, and that others have run into it.

**Comment by pernielsentikaer** [comment]
I made a PR to remove it #1982
