### ISSUE TITLE
Support for Renamer

### ISSUE THREAD

**Issue by niam0r** [lra/mackup#2032]
Hi, 

Thanks for this app.
It would be great to have [Renamer](https://renamer.com/) supported please 🙏 

I'll try and figure out custom 'DIY' settings in the meantime and post it here.

Thanks.

Romain

**Comment by niam0r** [comment]
I've just tried [these instructions](https://github.com/lra/mackup/tree/master/doc#add-support-for-an-application-or-almost-any-file-or-directory) and created `/Users/aero/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.mackup/renamer.cfg` with the following code:
```
[application]
name = Renamer

[configuration_files]
~/Library/Preferences/com.incrediblebee.Renamer6.plist
~/Library/Application Support/Renamer/
```
But it doesn't seem to work as I can't see the backed up files in the Mackup folder, any idea please ?

**Comment by Kol9yN** [comment]
problem in spaces
#1130
