### ISSUE TITLE
When will there be another release?

### ISSUE THREAD

**Issue by DevonFulcher** [lra/mackup#2039]
The last release, 0.8.40, was on Nov 5, 2023. I'm interested in using [the Cursor config](https://github.com/lra/mackup/pull/2020) without copy-pasting it myself or building Mackup from source. Is it time for another release?

**Comment by victor-falcon** [comment]
It seems that the development of mackup is kinda stopped right now :(

**Comment by lra** [comment]
It's based on reminders from people complaining.
j/k.
I'll do one today ;)

**Comment by lra** [comment]
Done: https://github.com/lra/mackup/releases/tag/0.8.41

Thanks for pushing!
