### ISSUE TITLE
Sublime text 3 only makes a backup of user/

### ISSUE THREAD

**Issue by stenehall** [lra/mackup#235]
The behavior of mackup for Sublime text 3 seems to have changed in 0.7. Now it only makes a backup of ~/Library/Application Support/Sublime Text 3/Packages/User and not the entire Sublime text 3 folder.

Since I have custom Packages that I'd like to keep in sync this really isn't ideal for me. Any suggestions?

**Comment by lra** [comment]
PR is up but needs some work: https://github.com/lra/mackup/pull/338
