### ISSUE TITLE
TextMate "Favorites" are symlinks - Mackup copies entire path into Dropbox

### ISSUE THREAD

**Issue by paste** [lra/mackup#249]
TextMate stores its Favorites as symlinks within the `~/Library/Application Support/TextMate/Favorites` directory:
![screenshot 2014-04-12 03 48 13](https://cloud.githubusercontent.com/assets/136583/2687070/612e5460-c232-11e3-8dcb-fda8a5b29f8b.png)

When Mackup tried to backup my TextMate configuration, the symlinks were expanded so that 20GB worth of "Favorites" were copied into Dropbox/Mackup.

Also, it's silly that you can't use the `mackup` command to backup and restore individual apps. Why can't I just do: `mackup restore TextMate`?

**Comment by lra** [comment]
Fixed in https://github.com/lra/mackup/commit/34b727be360f5c17396d5630ddeef12c55cb43e1
