### ISSUE TITLE
Mackup 0.7.3 contains incorrect Python path

### ISSUE THREAD

**Issue by commadelimited** [lra/mackup#263]
I just upgraded homebrew, then upgraded to mackup 0.7.3. I then tried running `mackup list` and got the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 23, in <module>
    import mackup.main
ImportError: No module named mackup.main
```

I dug into the code and when an import of mackup.main fails it attempts to build a system path which has Python 2.7 hardcoded (`/usr/local/Cellar/mackup/0.7.3/bin/mackup`):

```
hacky_packages_path = os.path.join(parent_dir_path, 'lib/python2.7/site-packages')
```

But for some reason my copy of 0.7.3 contains Python 2.6:

```
☀  ~  cd /usr/local/Cellar/mackup/
☀  mackup [master] tree -d
└── 0.7.3
    ├── bin
    └── lib
        └── python2.6
            └── site-packages
                └── mackup
                    └── applications
```

Do you have any ideas why that might have happened? My system Python is

```
☀  ~  python --version
Python 2.7.6
```

**Comment by lra** [comment]
I revamped the package structure, should be good now
