### ISSUE TITLE
Quadriplegic accessibility software called Keystrokes

### ISSUE THREAD

**Issue by escapologyBB** [lra/mackup#273]
Hello,

This is an awesome project, I'm quadriplegic and clicking and dragging to set up a new computer is so unbelievably difficult and boring that these commandline tools make my life about 47.2% easier.  I use voice dictation software you see, which means that I can input text into any application including the Terminal which is why these tools are so great.

I'm not a programmer so I have no real idea where to begin with this, but if someone could point me in the right direction I am happy to learn how to do it myself, obviously!

The two absolutely indispensable pieces of software for me are called [Keystrokes][1] and [DragonDictate for Mac][2].  Keystrokes is an on-screen keyboard which I use with a piece of hardware called the [TrackerPro][3], the TrackerPro tracks a reflective marker on my glasses so that if I look up and left that's where the cursor moves on screen.  Awesome Sauce as I only have control of my head and my index finger!

So after all that possibly pointless background, I really would like to know how to backup the settings for both of these applications.  I've worked out how to backup the odd dotfiles in my home folder, but I can't work out how to have Mackup backup settings for these two apps.  Can anybody help me with this?

Many thanks

Stuart

[1]: http://www.assistiveware.com/product/keystrokes
[2]: http://www.nuance.com/for-individuals/by-product/dragon-for-mac/dragon-dictate/index.htm
[3]: http://www.ablenetinc.com/Assistive-Technology/Computer-Access/TrackerPro

**Comment by lra** [comment]
Glad it helps ;)
You (or anyone else) can follow those instructions: https://github.com/lra/mackup/tree/master/doc#get-official-support-for-an-application
