### ISSUE TITLE
"Are you sure that your want to replace it?" <Yes|No>

### ISSUE THREAD

**Issue by ryanburnett** [lra/mackup#283]
When I `mackup backup` I receive this prompt for most files:

> A file named /Users/Ryan/Dropbox/Mackup/Library/Preferences/com.irradiatedsoftware.SizeUp.plist already exists in the backup.
Are you sure that your want to replace it ? \<Yes|No>

...I had to type `Yes` about 10 times. First world problems, I know ;)

* Anyway to add an `--overwrite` flag or similar to avoid having to type `Yes` for each updated file?
* *Spellcheck police* `your` should be `you` :)

Thanks for making mackup!

**Comment by Anahkiasen** [comment]
:+1: for a `--force` flag, always receiving prompts every time I backup from Popcorn Time and SourceTree

**Comment by drawcard** [comment]
I'd love this feature, I currently have to copy and paste the word "Yes" into the terminal repeatedly to stop these questions from coming up repeatedly.

**Comment by kiliankoe** [comment]
For things that require you to do this you can just pipe the output of yes into it ;)

`yes | mackup backup`

**Comment by drawcard** [comment]
Ah. Well that makes a lot of sense! :)

**Comment by lra** [comment]
Fixed by https://github.com/lra/mackup/pull/493
