### ISSUE TITLE
Partial .ssh folder sync

### ISSUE THREAD

**Issue by pdufour** [lra/mackup#318]
I could be totally missing something here, but I can't seem to do a partial `.ssh` folder sync.

When I run `mackup restore` it prompts me with "You already have a folder named .ssh in your home.
Do you want to replace it with your backup ?" and if I type in "Yes", it overrides the `.ssh` folder with a symlink to the one on mackup. Here is the relevant info:

`.mackup.cfg`

````
[storage]
engine = file_system
path = .dotfiles
directory = mackup

[applications_to_sync]
local-ssh
````

`.mackup/local-ssh.cfg`

````
[application]
name = local-ssh

[configuration_files]
.ssh/config
````

`~/.dotfiles`

````
    mackup
        .ssh
            config
            known_hosts
````

**Comment by lra** [comment]
Fixed in https://github.com/lra/mackup/commit/be67f6f582ce44d907d98f505f4aeffc9879e5c5
