### ISSUE TITLE
.ssh directory copied by default

### ISSUE THREAD

**Issue by lambdahands** [lra/mackup#336]
Loving this project so far, but I noticed my `~/.ssh` directory including my `id_rsa` were copied by default to my Dropbox account. This is, well, uncomfortable. It may be best to disable backing up keys to a cloud service by default.

**Comment by llinder** [comment]
Optionally encrypting files might be a good approach?  This way storing these files in dropbox is less worrisome.

**Comment by lra** [comment]
Dupe of https://github.com/lra/mackup/issues/109
