### ISSUE TITLE
Feature request for .mackup.cfg to have section for individual files

### ISSUE THREAD

**Issue by ChristopherA** [lra/mackup#346]
I have some specific files, not apps, that I would like mackup to sync. For instance, in my [dotfiles project](https://github.com/christophera/dotfiles) I have a special file `.bash_profile.local` that is not backed up to my personal .dotfiles repository as it contains private info. This is a great candidate for putting in my private dropbox instead.

Something along the lines of this entry in `.mackup.cfg`
```
[files_to_sync]
~/.bash_profile.local
```
-- Christopher Allen

**Comment by lra** [comment]
@ChristopherA Should not be a problem, Mackup's config files are synced like the rest: https://github.com/lra/mackup/blob/master/mackup/applications/mackup.cfg
