### ISSUE TITLE
Files backed up that are not in .mackup.cfg [applications_to_sync]

### ISSUE THREAD

**Issue by ChristopherA** [lra/mackup#349]
When I tried my first restore on a new machine (after applying the two-line patch to python), I have two restores were not in my config:
```
Restoring .gemrc...
Restoring .zshrc...
```
These are what I have in my .mackup.cfg
```
[applications_to_sync]
atom
mailplane
sizeup
transmission
ssh
```
You should not be backing up and restoring files that I didn't request to backup.

**Comment by lra** [comment]
@ChristopherA should have been fixed a while ago (January) by https://github.com/lra/mackup/commit/691ca2009ae0c2be91553b948b52485172c49f8c

Please comment back if it's not the case.
