### ISSUE TITLE
Viscosity syncs .Sparkle directory

### ISSUE THREAD

**Issue by danielcompton** [lra/mackup#364]
Viscosity backups include the .Sparkle directory in Application Support. I've emailed the developer to ask them to move it but in the meantime, can we exclude it somehow? Viscosity was added in #45.

**Comment by lra** [comment]
Should we exclude `Library/Application Support/Viscosity` from https://github.com/lra/mackup/blob/master/mackup/applications/viscosity.cfg ?

**Comment by danielcompton** [comment]
We really just want to exclude .Sparkle folders everywhere, the App Support folder itself is fine.

**Comment by lra** [comment]
The actual engine does not support exclusion, so we'll have to explicitly list everything we want to sync.
Anyone can provide an updated https://github.com/lra/mackup/blob/master/mackup/applications/viscosity.cfg ?

**Comment by anthonysomerset** [comment]
I dunno if TunnelBlick or other connections get handled differently but one could just include `Library/Application Support/Viscosity/OpenVPN` only which then effectively doesn't backup the `.Sparkle` folder but still gets everything important

i think this might still be a bug with Viscosity though - i did a quick find in my directories for all folders named `.Sparkle` and all of the others were empty such as VLC etc

**Comment by danielcompton** [comment]
This isn't fixed in the general case, only in the specific case of OpenVPN.

**Comment by lra** [comment]
We can't exclude `.Sparkle` in a linked folder, if you link a directory, you link it with all its content.
To do such a thing, we would need to:
1. Implement a copy engine (vs link)
2. Implement file exclusion in the config

I feel like this sparkle stuff should live outside of the config...

**Comment by danielcompton** [comment]
Sparkle moves their stuff outside of config since https://github.com/sparkle-project/Sparkle/issues/146, but not all apps have updated to the new Sparkle versions that support it.

**Comment by lra** [comment]
cool, let's wait for this to happen given the amount of work it would require on Mackup.
