### ISSUE TITLE
Should iTerm2 be removed

### ISSUE THREAD

**Issue by scottsuch** [lra/mackup#367]
According to the policy in the [CONTRIBUTING.md](https://github.com/lra/mackup/blob/master/CHANGELOG.md), iTerm2 already provides it's own method of syncing preferences. It's not a huge deal as I just tell it to use the same location as what Mackup defaults to.

![preferences_and_new_issue_ _lra_mackup](https://cloud.githubusercontent.com/assets/897179/4608868/31632e3c-528c-11e4-8987-e1adce9b938b.png)

**Comment by ponychicken** [comment]
According to the new contribution guidelines, i think this can be closed.
