### ISSUE TITLE
Public safety

### ISSUE THREAD

**Issue by afeld** [lra/mackup#372]
I have a [dotfiles](https://github.com/afeld/dotfiles) repository that I keep public and up-to-date. I am very interested in using mackup instead of [a cobbled-together symlink script](https://github.com/afeld/dotfiles/blob/master/init.sh), but am concerned about all of the new files that would be publicly visible by storing the mackup files there. Are any of the application settings synced by mackup known to be sensitive information/credentials, or should it all be theoretically public-friendly? Might be worth adding a note to the README of whether the information should be safe for public viewing, or if that's not a priority. Thanks!

**Comment by glaszig** [comment]
i'd use my `~/Mackup` store as a git repo on top with a very sensible `.gitignore` and have my sync service keep my settings in sync and just `git push` the files i specifically want to end up in my public git repo.

**Comment by ToostInc** [comment]
Like with anything you put out on the internet, if you don't forget to use common sense you'll be fine. 

Mackup is essentially a more manageable version of your cobbled together symlink script. You still have to choose which dotfiles it syncs, and if there's anything you don't like, you can easily disable or change them.

Nevertheless, how and where you synchronise your files is your responsibility. Don't put personal files in a public repo.

**Comment by lra** [comment]
The default changed in https://github.com/lra/mackup/commit/b2847f5750304cfd388ced4cf33bb14a3767c239

**Comment by lra** [comment]
If you want us to add a warning text, feel free to do a PR about it or let us know what would have helped.

At some point, I feel like adding too much text is counter productive and people won't read it.
