### ISSUE TITLE
Add support for customized Color Palettes in the Picker

### ISSUE THREAD

**Issue by Joshfindit** [lra/mackup#378]
In Yosemite and Mavericks, custom color palettes are stored in ~/Library/Colors/

**Comment by Joshfindit** [comment]
I'm sad to report that in 10.11 Beta (15A234d), the color picker does not read custom color palettes when the ~/Library/Colors/ folder is symlinked.

To reproduce:
1. Open a file in Preview
2. Open the color picker (Show Markup Toolbar > Stroke or Fill > Show Colors... )
3. Go to the 'Color Palettes' tab
4. Create a new palette and add a couple colors
5. Quit Preview
6. Reopen Preview and verify that the palette is there
7. Quit preview
8. Go to ~/Library/Colors and see the custom palette (usually "Untitled.clr")
9. Move the Colors folder to ~/Dropbox/Mackup/Library/
10. in Terminal, run 'ln -s ~/Dropbox/Mackup/Library/Colors ~/Library/'
11. Verify that the alias is in ~/Library and that the .clr file is there
12. Open an image in Preview, and open the Color Picker

Expected result: The custom palette is listed and available
Actual result: The custom palette is missing, only the defaults are shown. Additionally, any newly created palettes are not saved.

**Comment by lra** [comment]
It will have to wait for the copy mode then =/ https://github.com/lra/mackup/issues/613
