### ISSUE TITLE
iTerm 2 overwrites symlink

### ISSUE THREAD

**Issue by ponychicken** [lra/mackup#382]
On running mackup backup(in Terminal, iTerm is not running):
`````
A file named /Users/moniker/Dropbox/Mackup/Library/Preferences/com.googlecode.iterm2.plist already exists in the backup.
Are you sure that your want to replace it ? <Yes|No>Yes
````
After starting iTerm2 again and changing some pref:
`````
ls -lah /Users/moniker/Dropbox/Mackup/Library/Preferences/com.googlecode.iterm2.plist
-rw-------  1 user  staff    47K Oct 26 15:10 Library/Preferences/com.googlecode.iterm2.plist
`````
iTerm2 immediately overwrote the file instead of following the link.

**Comment by jacinto123** [comment]
I get the same issue, where you able to solve this?

**Comment by ponychicken** [comment]
No, I didn't solve it. But it's not really anything mackup can do, it's a defect with iTerm2.

**Comment by adamlogic** [comment]
I'm seeing this as well. To get around it, I've [configured Mackup to ignore](https://github.com/lra/mackup/tree/master/doc#dont-sync-an-application) iterm2 and am using iTerm's own method of syncing instead (see #367).

**Comment by lra** [comment]
Anyone feels like creating a PR to remove its support?

**Comment by akabab** [comment]
iterm caches defaults, to solve this:
1. quit iterm2
2. mackup restore (override `com.googlecode.iterm2.plist` -> Yes)
3. run command `killall cfprefsd`
4. open iterm2

[source](http://apple.stackexchange.com/questions/111534/iterm2-doesnt-read-com-googlecode-iterm2-plist)

**Comment by jamiew** [comment]
is this default-on in iTerm2 now? I used both mackup and iTerm2 for ages, but appear to have this disabled:

<img width="897" alt="CleanShot 2023-10-25 at 09 21 02@2x" src="https://github.com/lra/mackup/assets/1903/917f8d9e-6791-4c5b-99f4-0877e9219149">

or is the roto issue really this "iTerm2 was running in background and overrode symlink" like @akabab mentions? Not sure how to avoid that without trying to add some force-kill magic, which afaik mackup doesn't really have existing support for
