### ISSUE TITLE
New driver support : baidu disk

### ISSUE THREAD

**Issue by nateriver520** [lra/mackup#436]
Since a lot of users use baidu disk as default disk. 
Could I send a PR to let user choose baidu disk as storage engine ?

**Comment by lra** [comment]
It does not hurt to have more buitins engine supports, go ahead =)

**Comment by nateriver520** [comment]
Okay, I will finish this feature this week :)

**Comment by lra** [comment]
no rush, I'm behind in the merges =)

On Sun, Jan 4, 2015 at 2:08 AM, Shuo Yang <notifications@github.com> wrote:

> Okay, I will finish this feature this week :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lra/mackup/issues/436#issuecomment-68623718>.
>



-- 
Laurent Raufaste
<http://www.glop.org/>

**Comment by lra** [comment]
FYI I just merged a new engine for Copy, you can take a look https://github.com/lra/mackup/commit/0f36b547da56155b26e4dbed95151586ebed80b9

**Comment by lra** [comment]
Feel free to open a PR.
