### ISSUE TITLE
The MacOSX Application Backs Up ColorSync Settings

### ISSUE THREAD

**Issue by devnulled** [lra/mackup#438]
Long story short, I have a sandboxed app from the Mac AppStore which needs to be able to access ColorSync settings to work.  The app is Voila!, a popular screencap app.  It can't access the profiles because it is sandboxed and can only access real files under Library/ColorSync and macup symlinks these files using the "MacOSX" application.

I'd rather it be separated into its own app called ColorSync so that I can just ignore the ColorSync app and continue to backup MacOSX.

I already have a commit ready for this and will be submitting a pull request soon.

**Comment by lra** [comment]
Should be fixed by https://github.com/lra/mackup/pull/439
