### ISSUE TITLE
Backup to multiple locations by application?

### ISSUE THREAD

**Issue by nfarrar** [lra/mackup#442]
I keep some of my configs in a public git repository - but due to the sensitive nature of some of the configurations, I don't want to put them all there.

I looked through the docs to see if there was a way to force some of the configs to be backed up to a separate location, but didn't see anything obvious. Am I missing it, or is this not possible?

ATM I'm using my own bash script that differentiates:

    $HOME/.dotfiles  # non-sensitive configuration files like .bash_profile, .bashrc, stored in public git repo
    $HOME/.secrets   # encrypt filesystem container containing gpg keys, ssh keys, api tokens, etc

If this is possible, I'd like to switch to mackup.

**Comment by lra** [comment]
Not possible as it is, but could be doable with some work.
But 1st we need to define how it would work: merge? replace?

**Comment by lra** [comment]
Thinking about it more, I don't see a simple way to declare such a thing, sorry.
