### ISSUE TITLE
Message.cfg cause app has no permission to open applescript directory

### ISSUE THREAD

**Issue by morphinewan** [lra/mackup#444]
I think all the script under "~/Library/Application Scripts/com.apple.iChat/" should not be synced. 
![2015-01-26 1 39 55](https://cloud.githubusercontent.com/assets/458887/5895658/d9eb4892-a560-11e4-99c3-6be56bbc3956.png)

**Comment by lra** [comment]
@vitorgalvao you seem to know Apple Messages per https://github.com/lra/mackup/commits/master/mackup/applications/messages.cfg
Do you think we should remove it all?

**Comment by vitorgalvao** [comment]
I don’t use Messages scripts and am not sure how prevalent they are in user’s machines. A single script causing errors also doesn’t mean much; maybe it is the least popular and only Messages script in existence that causes the problem, so it wouldn’t make much sense to “punish” all the others for it.

Some context would be appreciated, @morphinewan. I can’t read that message and will venture a guess that @lra can’t either. Being a screenshot it also means we can’t even copy it to translate with a piece of software. What does the error say, exactly? And which script is it, where did you get it from?

**Comment by morphinewan** [comment]
@vitorgalvao I will describe the issue more detail for you. You can open the preference panel in Message.app. You can see snapshot like below. All the apple script file stored in ~/Library/Application Scripts/com.apple.iChat/ will be appended to the dropdown list to be selected by user.
![2015-01-27 6 00 48](https://cloud.githubusercontent.com/assets/458887/5909316/67dd6674-a5ea-11e4-89d6-07bfdabb4491.png)

![2015-01-27 6 08 29](https://cloud.githubusercontent.com/assets/458887/5909372/f569cb0e-a5ea-11e4-862c-748b27bb4549.png)

If the directory is replaced by a symbolic link, Message.app will report no permission to open the directory and the dropdown list will be empty.

I think Message.app just can't use this directory  as a link, it should not be synced in makeup.

Sorry for the inconvenience of my system snapshot language if it is bothering you. Anything should be translated for you, please tell me.

**Comment by vitorgalvao** [comment]
Ah, it’s clear now, thank you for the explanation. Seems like the issue is only with linking, so the directory could be [synced with copying](https://github.com/lra/mackup/issues/195) only.

**Comment by lra** [comment]
Should we remove it then?

**Comment by vitorgalvao** [comment]
Seems like it, yes. I linked to the copying issue because you mentioned [copying could be done in the apps that needed](https://github.com/lra/mackup/issues/195#issuecomment-33308596). Alternatively this could be commented out, and if copying becomes something not app-specific but a setting inside the `.cfg` files themselves, it could be leveraged then.

**Comment by lra** [comment]
I'd rather not add WIP to master to not confuse possible contributors. Feel free to keep a list around (e.g in an issue)

Feel free to open a PR to clean the Messages config.

**Comment by lra** [comment]
You'll have to wait the next release, until then, you can specify a custom config to fix this.

**Comment by morphinewan** [comment]
Thank you both.
