### ISSUE TITLE
Support OS X system apps: Dock and Finder

### ISSUE THREAD

**Issue by mankoff** [lra/mackup#446]
It would be nice to have the Finder and Dock preferences backed up and synced.

**Comment by glaszig** [comment]
just a note, without testing: i would need to log out and back into os x if settings change on a remote machine, right?

**Comment by mankoff** [comment]
Depends what settings. I change Dock settings on the command line and then `killall Dock` to make them take effect.

**Comment by revolter** [comment]
@mankoff, Could you provide the location of the actual file where these are saved?

**Comment by mankoff** [comment]
~/Library/Preferences/com.apple.dock.plist
    ~/Library/Preferences/com.apple.Dock.plist
    ~/Library/Preferences/com.apple.finder.plist
    
OS X is usually case-insensitive, but I run mine case sensitive. I'm not sure if `dock` or `Dock` would exist on a case-insensitive system.

**Comment by Joshfindit** [comment]
The file created by default on a case-insensitive system is ```~/Library/Preferences/com.apple.dock.plist```

**Comment by revolter** [comment]
I could make a PR to add these, but I realize is not necessarily a good idea, because, for example, I have a different set of pinned apps in the dock at work vs home. You could use:

```
[applications_to_ignore]
macosx
```

but this would ignore __all__ settings.

@lra, would it be a possibility for applications configuration files to look like this:

```
[application]
name = MacOSX

[configuration_files]
[general]
.MacOSX
[shortcuts]
Library/KeyBindings/DefaultKeyBinding.dict
Library/Preferences/com.apple.symbolichotkeys.plist
[dock]
Library/Preferences/com.apple.dock.plist
[finder]
Library/Preferences/com.apple.finder.plist
```

so one could disable dock settings backup using:

```
[applications_to_ignore]
macosx.dock
```
?

**Comment by lra** [comment]
It would be possible, but rather confusing.
To keep it simple, what about having different configurations for each app?
For now as mackup is enabling everything by default, it would have to be a user config, until mackup allow to selectively enable/disable apps.

**Comment by Joshfindit** [comment]
It seems like this is a crossroad situation;
Either add configurations like this that could cause confusion and/or visual cruft for some users, or;
find some other way to embrace them.

Realistically, there could be a wiki, a separate folder on the repo, etc. that documents anything that may be for a select few.

**Comment by lra** [comment]
I agree, or once mackup does not sync everything by default, we could have apps like `osx-shortcuts`, `osx-doc`, ...
Anyway, not possible until at least https://github.com/lra/mackup/issues/614
