### ISSUE TITLE
TextMate 2 syncing seems broke ruby runtime

### ISSUE THREAD

**Issue by morphinewan** [lra/mackup#449]
I use [ctrl + cmd + o] to open a terminal frequently. But I found out that the ruby runtime it depends on will be broken after I synced TextMate 2 configuration files.

Is this some kind of a bug?

**Comment by morphinewan** [comment]
When I run open terminal function at the first time, it will install a ruby runtime in to Library/Application Support/TextMate/Ruby.

It seems make Library/Application Support/TextMate a symbolic link will make TextMate 2 can't use its ruby installed inside properly.

**Comment by graeson** [comment]
After installing mackup and running `mackup backup`, textmate throws the following error: "Failure running 'Comment Selection'. env: ruby 18: Permission Denied"

**Comment by jrk** [comment]
+1 this is a huge problem for me. It breaks a very large number of core TextMate operations.

**Comment by lra** [comment]
Should we remove `Library/Application Support/TextMate` from https://github.com/lra/mackup/blob/master/mackup/applications/textmate.cfg to not sync it?

**Comment by nicolinuxfr** [comment]
I think I have the same problem… still. Maybe it's because I synced TextMate before the fix ?

But in the Mackup folder, I only saw bundles and not the whole TextMate folder, so I don't understand what happens…

**Comment by joshS314159** [comment]
I'm encountering this same error with Textmate once I run backup: `"Failure running 'Comment Selection'. env: ruby 18: Permission Denied"`.

Does anyone have a solution?

**Comment by nicolinuxfr** [comment]
No real solution, but here's what I do when it happens : edit the command, and change `ruby18` to just `ruby` at the end of first line.

For me, it was a working fix each time. And I have not seen any functional difference after the change.

**Comment by joshS314159** [comment]
Thanks! That was a real easy fix.

**Comment by jrk** [comment]
The issue seems to be that sync services aren't always preserving the execute permission bits on synced files. The more direct fix is:

```bash
$ cd Mackup/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/bin
$ chmod +x *
```

**Comment by nicolinuxfr** [comment]
Indeed, I can confirm it works.

So, is it a bad idea to use Mackup ? If it changes execute permission each times, it will be a nightmare…

**Comment by miguelandres** [comment]
This is still happening, using google drive at least
