### ISSUE TITLE
Mackup restore ignores the [applications_to_ignore] config?

### ISSUE THREAD

**Issue by Cadair** [lra/mackup#453]
Hello,

I have some packages in [applications_to_ignore] for which I have my own custom versions. When I run `mackup backup` the custom versions work fine but when I run `mackup restore` it seems to ignore this and try and use both the originals and the custom ones.

**Comment by lra** [comment]
Can you clarify what you mean by "which I have my own custom versions"? If you ignore them why do you customize them?

Also are you running 0.8.2? A bunch of config related bugs have been fixed lately

**Comment by Cadair** [comment]
I have a custom ssh and vim backup defined, but I named them myvim and myssh so that I could see what was happening a bit better (and I only read the overwrite comment in the docs later). I ignore the originals, which backup the whole `.ssh` folder and parts of `.vim` and myssh only backs up `.ssh/config` and myvim backups all of `.vim`.

When I run restore the first question is it asking me to overwrite the whole `.ssh` folder, then later on it asks me to overwrite the `.vim/bundle` etc. folders.

I am only running 0.7.4 it looks like the AUR package is a little out of date, I will upgrade.

**Comment by lra** [comment]
You should, most of the config mess stuff has been fixed since.

**Comment by Cadair** [comment]
The update fixed it, thanks.

**Comment by lra** [comment]
cool
