### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by yangm97** [lra/mackup#456]
This will show how simple it is to get extensions synced: http://shaneo.net/post/52976619502/syncing-safari-extensions-on-the-mac-using-dropbox
While it would be good to have extensions synced, I would also like to ask about Safari's own settings and extensions settings.
The goal is to make a single PR with 100% Safari support.

**Comment by kfinlay** [comment]
I've tested this out with a custom Mackup config. It doesn't work. Safari uninstalls on restart even with working links and with the extensions folder fully synced.

**Comment by lra** [comment]
closing until there is a proven way to sync Safari's extensions.
