### ISSUE TITLE
Option to exclude some files

### ISSUE THREAD

**Issue by ponychicken** [lra/mackup#463]
An exclude statement would make it easier to selectively disable syncing some file in a folder.

I imagine it could look a bit like:

````
[configuration_files]
/blah/folder

[exluded_files]
/blah/folder/tempfile

**Comment by lra** [comment]
not possible, what do you link then? `*`?

**Comment by ponychicken** [comment]
Would it not be possible like this?:




1. Stat the directory and collect a list of all files

2. Remove from this list the excluded files

3. Create links for each of the remaining entries

**Comment by ponychicken** [comment]
Would you accept such a PR?

**Comment by lra** [comment]
No because the setup is only done on `mackup backup`, and not done anymore later. And some application might add new files later on that would never be synced.

**Comment by LandonSchropp** [comment]
:+1: to this suggestion. I have a few sensitive keys on my work computer (AWS CLI keys) that I don't want to sync with my home machine. It would be nice to have a configuration file with options to exclude certain applications.

**Comment by lra** [comment]
Dupe of https://github.com/lra/mackup/issues/602
