### ISSUE TITLE
Custom files/directories

### ISSUE THREAD

**Issue by churnd** [lra/mackup#474]
Trying to add some custom files/directories:

```
cat .mackup/files.cfg 
[application]
name = home

[configuration_files]
abin
.x2goclient
.tm_properties
Sites
```
`mackup list` shows the config:
```
mackup list | grep files
 - files
```
Running `mackup backup` doesn't grab them.  Am I doing it wrong?  I have the latest from homebrew as of this posting.

**Comment by churnd** [comment]
Nevermind, got it working.  Typo on my part.

**Comment by lra** [comment]
Thx, closing this then =)
