### ISSUE TITLE
No graceful error management

### ISSUE THREAD

**Issue by sieben** [lra/mackup#479]
I get the following error out of the box:

shutil.Error: [('/home/sieben/.byobu/.ssh-agent', '/home/sieben/Dropbox/Mackup/.byobu/.ssh-agent', "[Errno 2] No such file or directory: '/home/sieben/.byobu/.ssh-agent'")]

**Comment by lra** [comment]
What kind of graceful error management would you expect to see?

**Comment by neil-greenwood** [comment]
I think this file should be excluded. I have a patch to ignore that file. I'm just preparing the PR now...

**Comment by lra** [comment]
should be fixed by https://github.com/lra/mackup/pull/759
