### ISSUE TITLE
Feature request: Backup system Keyboard Shortcuts

### ISSUE THREAD

**Issue by modest** [lra/mackup#482]
~/Library/Preferences/com.apple.symbolichotkeys.plist

This is where all of the user's global (non-app-specific) hotkeys are stored.

![settings](https://cloud.githubusercontent.com/assets/990299/6544507/30e01490-c508-11e4-9d44-5caedd1dad23.png)

**Comment by LeonardoGentile** [comment]
+1

**Comment by LeonardoGentile** [comment]
What about app-specific? Would it be too difficult to track?

**Comment by modest** [comment]
I'd love it, but it's hard.  App-specific overrides ("App Shortcuts" tab) are stored in the preferences file for each individual app.  OS X inserts a `NSUserKeyEquivalents` dictionary into the plist of every single app that you edit.  Kind of a crazy solution, but I can see the rationale.

So, you could take a few different approaches:

- Wait for each app to be individually supported by mackup, and include their Preferences plist (most already do.) This will include your overrides. For example, [Spotify's mackup configuration](https://github.com/lra/mackup/blob/master/mackup/applications/spotify.cfg) includes the plist.
- Add a new engine to mackup to backup keyboards shortcuts separately.  You would probably need to crawl through the user's Preferences folder for plist's, extract the `NSUserKeyEquivalents` dictionary from each plist, and store them in some centralized file. (Then, on restore, you'd need to inject those back into the plist files of every app.)
- Just backup all Preferences.

In my opinion, mackup is currently optimized for non-standard settings files, such as command line tools.  If mackup wants to back up the settings & data of all well-behaved GUI apps, too, there are potentially some better automatic approaches that don't require manual work (custom config files) for every single app.  That might be treading too dangerously close to a fully-functional system backup tool, though.

**Comment by vitorgalvao** [comment]
Honestly, for these types of configurations, I think syncing is a mistake. Not only is it error prone, it’s an insane amount of work. Instead, [set whatever you want in a script and run it when needed](https://github.com/vitorgalvao/dotfiles/blob/master/scripts/03_configs.sh#L22L39).

Just like with something like Atom, syncing the directory with the actual plugins can also lead to issues and is also a mistake, that’s what `apm` is for. Syncing should be the last resort, the first being to automate the app’s commands.

**Comment by aristidesfl** [comment]
Has anyone attempted to sync `~/Library/Preferences/com.apple.symbolichotkeys.plist` between El Capitan and Sierra?
