### ISSUE TITLE
Incorrect path in Yosemite and Google Drive Version 1.20.8672.3137

### ISSUE THREAD

**Issue by lauborges** [lra/mackup#497]
variable gdrive_db_path expected 'Library/Application Support/Google/Drive/sync_config.db' 
but the correct path is 'Library/Application Support/Google/Drive/user_default/sync_config.db'

**Comment by beck** [comment]
:star:

**Comment by lra** [comment]
It recently changed? Do we need to support both and we can expect all gdrive to be up to date?
Feel free to open a PR anyone

**Comment by varunyellina** [comment]
I have the same version and i'm unable to backup nor restore.
   > mackup backup
   Error: Unable to find your Google Drive install =(

**Comment by garnett** [comment]
Any updates with this?

**Comment by lra** [comment]
Sorry I don't have the time to do a PR

**Comment by seanfreiburg** [comment]
Seeing the same thing. I'm thinking you try the  'Library/Application Support/Google/Drive/sync_config.db' 
path and then 'Library/Application Support/Google/Drive/user_default/sync_config.db' . If the both fail, throw the error.

**Comment by lra** [comment]
Fixed in https://github.com/lra/mackup/pull/575
