### ISSUE TITLE
Lightroom CC 2015 Crashes

### ISSUE THREAD

**Issue by chibicode** [lra/mackup#528]
I upgraded to Lightroom CC (2015, [just released](http://venturebeat.com/2015/04/21/adobe-launches-lightroom-cc-with-facial-recognition-gpu-enhancements-new-android-features/)), but with mackup it crashes as soon as it launches. It seems that the new preferences file, `com.adobe.Lightroom6.plist` is symlinking to `com.adobe.Lightroom5.plist` for some reason.

It'd be great if someone else can confirm this.

**Comment by Dremora** [comment]
My Lightroom crashes as well, but I don't think it's related to the symlink. The symlink has likely been created by Lightroom itself, getting rid of it doesn't help. What is helping me, however, is starting Lightroom while holding the Option key and choosing catalog from the list. Not sure if our crashes are related though, but give it a go.

**Comment by iansoper** [comment]
I had the same issue. When i uninstalled mackup Lightroom launched just fine.

**Comment by drawcard** [comment]
Happened to me too, had to tell Mackup to ignore Lightroom.

**Comment by lra** [comment]
Should we remove support for LR?

**Comment by chibicode** [comment]
:+1: for removing the support for LR @Ira

**Comment by lra** [comment]
https://github.com/lra/mackup/commit/7dee92d20cd9fff6538fcd11543f2bd488684409

**Comment by chibicode** [comment]
@lra thanks!
