### ISSUE TITLE
Install on Linux not working

### ISSUE THREAD

**Issue by arianmaykon** [lra/mackup#535]
Trying to install on Linux through pip seems to process fine, but the executable is not available on the system PATH, and can't find it through find command. And following the install doc to use without pip, the path /bin on the master do not exist as well.

Any ideas?

**Comment by lra** [comment]
Might be a mistake on our side. Can you give us more info? (distribution, pip version, ...)

**Comment by arianmaykon** [comment]
Sure.

S.O.: Ubuntu 15.04 (64bits)
pip version: 7.0.3
Python 2.7

**Comment by lra** [comment]
Sorry but I can't reproduce this. Tried on a pristine 15.04:
```bash
vagrant@vagrant-ubuntu-vivid-64:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
vagrant@vagrant-ubuntu-vivid-64:~$ python --version
Python 2.7.9
vagrant@vagrant-ubuntu-vivid-64:~$ pip --version
pip 7.1.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
vagrant@vagrant-ubuntu-vivid-64:~$ sudo pip install mackup
Collecting mackup
  Downloading mackup-0.8.10.tar.gz
Requirement already satisfied (use --upgrade to upgrade): docopt in /usr/local/lib/python2.7/dist-packages (from mackup)
Installing collected packages: mackup
  Running setup.py install for mackup
Successfully installed mackup-0.8.10
vagrant@vagrant-ubuntu-vivid-64:~$ mackup 
Usage:
  mackup list
  mackup [options] backup
  mackup [options] restore
  mackup [options] uninstall
  mackup (-h | --help)
  mackup --version
vagrant@vagrant-ubuntu-vivid-64:~$ which mackup
/usr/local/bin/mackup
vagrant@vagrant-ubuntu-vivid-64:~$ 
```

**Comment by ahmadnassri** [comment]
for future readers:

had the same issue, after installing using `pip`, `mackup` was not found in the execution path.

turns out `pip` installs under `~/.local/bin/`, make sure you add that to your `PATH` and all is well.
