### ISSUE TITLE
applications_to_ignore not working

### ISSUE THREAD

**Issue by bugmelody** [lra/mackup#546]
fedora21
I add vim to applications_to_ignore,but 

$ mackup list | grep vim
 - macvim
 - vim
 - vimperator

still list it,  and `mackup backup` do nothing to vim

~/.mackup.cfg

[storage]
engine = file_system
path = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
directory = backup

[applications_to_sync]

[applications_to_ignore]
vim

**Comment by chadluo** [comment]
You should capitalize the name, see https://github.com/lra/mackup/blob/master/mackup/applications/vim.cfg#L2

**Comment by lra** [comment]
mmmh, not sure, you should use the canonical name (the file name in `mackup list`)
Might be a legit bug, if anyone want to look into it and fix it.

**Comment by lra** [comment]
`mackup list` is built to display all applications supported by mackup.
I think what you are looking for is a list of applications that mackup plans to scan based on your config.
This is not implemented yet, TODO: https://github.com/lra/mackup/issues/603
