### ISSUE TITLE
Documentation request: Use mackup before/after installing apps?

### ISSUE THREAD

**Issue by pikeas** [lra/mackup#548]
Should `mackup restore` be run on a clean machine before reinstalling apps, or after reinstalling them? Does it make a difference, either generally or on an app-by-app basis?

I'm configuring a new machine as we speak, and checked the Github repo for a recommendation on ordering. I'm leaning towards mackup THEN apps, but it would be great if the README had a note about this.

**Comment by lra** [comment]
It does not make a difference, as `mackup restore` just overwrites your app conf.
Feel free to open a PR to update the doc.
