### ISSUE TITLE
Custom Directory

### ISSUE THREAD

**Issue by forumware** [lra/mackup#549]
Hi I'm trying to add custom directories in mackup for backup.

~/.mackup/my-files.cfg

---Start---
[application]
name = /Users/ab/Desktop
name  = /Users/ab/Documents 
----End----

But when i run "mackup backup" these folders are not getting backed up. Can you help with what I'm doing wrong. 

Thanks,

FW

**Comment by lra** [comment]
Alway use relative folder, never absolute.

**Comment by forumware** [comment]
Thanks for the help, unfortunately i'm still having problems

Testing the path:

mc11:~ us3r$ ls .mackup
my-files.cfg
mc11:~ us3r$ cd .mackup
mc11:.mackup us3r$ ls
my-files.cfg
mc11:.mackup us3r$ pwd
/Users/us3r/.mackup
mc11:.mackup us3r$ cd ../Desktop 
mc11:Desktop us3r$ pwd
/Users/us3r/Desktop
mc11:Desktop us3r$

In my-files.cfg currently i have: 

[application]
name = ../Desktop

but still no luck when i'm backing up. I use the relative pack from where my-files.cfg is located?

**Comment by lra** [comment]
```
[application]
name = ../Desktop
```
Sorry I have a hard time following you. An application named `../Desktop`?

you have some doc here: https://github.com/lra/mackup/tree/master/doc#add-support-for-an-application-or-any-file-or-directory

**Comment by forumware** [comment]
I was under the impression that I could backup custom directories as well, wanted the same desktop folders, files on all the computers...

Am I reading that incorrect?

Thanks again and awesome app btw!!

**Comment by lra** [comment]
anything in your home, but you need to follow the documentation, "[application] name = ../Desktop" does not make sense.
