### ISSUE TITLE
Uninstall didn't delete mackup folder

### ISSUE THREAD

**Issue by aristidesfl** [lra/mackup#558]
I just installed mackup and did:

1. backup
2. uninstall
3. backup

Now it is telling me that the files already exist in `~/Dropbox/Mackup/...`

**Comment by lra** [comment]
It is not suppoed to delete this folder as people would yell at Mackup for loosing if it would.
If the community as a strong opinion about this, we can change it.

**Comment by aristidesfl** [comment]
The only reason I asked is because it is documented in the readme: https://github.com/lra/mackup#usage

**Comment by lra** [comment]
You are right, I updated it, I planned to do this at the beginning, but if you remove the Mackup folder on one computer, all the other synced computers will miss the files.

So I don't think it's easily feasible, any idea?

**Comment by aristidesfl** [comment]
Not really, seems the right thing to do.
