### ISSUE TITLE
Need Instructions in INSTALL.md For Running Locally?

### ISSUE THREAD

**Issue by devnulled** [lra/mackup#566]
I have a local fork of mackup that I cloned and have modified.  I need instructions on how to run it locally to test as I don't know the nuances between mackup, MacOs, and Python to know how to run it from master.  Thanks!

**Comment by lra** [comment]
you should be able to run `make develop` to test locally, and `make undevelop` to clean up.
https://github.com/lra/mackup/blob/master/Makefile

**Comment by lra** [comment]
feel free to update the doc

**Comment by revolter** [comment]
@Ira, then what?

**Comment by lra** [comment]
what is you question?

**Comment by revolter** [comment]
@lra, After running `make develop`, what do I do? I tried running `python mackup.py backup` but I get this error:

> Traceback (most recent call last):
>   File "/Users/Iulian/Documents/Repositories/revolter/mackup/mackup/mackup.py", line 13, in <module>
>     from . import utils
> ValueError: Attempted relative import in non-package

**Comment by lra** [comment]
`make develop` installs the dev version on your system. You should be able to just do `mackup` and it will run the version based on the files you've cloned.
`make develop` to clean things up and leave space on your system for the official version.

**Comment by revolter** [comment]
Ahaaa, I understand now. I don't have any better way for it, just add this perfect explanation to the `README` file. I thought that I have to directly run the local program, not that it replaces it and then `mackup` points to the local version.

**Comment by lra** [comment]
mind doing a PR to add it?
I'd rather have someone else do it to make sure it's understandable =)

**Comment by revolter** [comment]
@lra, Is [this](https://github.com/lra/mackup/pull/639) ok?
