### ISSUE TITLE
the latest version of mackup?

### ISSUE THREAD

**Issue by VMatrix1900** [lra/mackup#571]
I use `Homebrew` to install latest version of mackup(0.8.5). But I can't backup spacemacs, which is surpported by #537. `Homebrew` use package in PyPi to get the latest version. But it seems out of date.
Can you upgrade it? Or should I use `brew install mackup --HEAD` to get the latest mackup?

**Comment by joeyhoer** [comment]
This is true. It appears that commit was added in April whereas the last release (0.8.5) was released in March. If you want support/access to that specific feature/commit, you'll have to use the `HEAD` version.

**Comment by VMatrix1900** [comment]
So when will be the next release?

**Comment by lra** [comment]
Done, 0.8.6 is out https://pypi.python.org/pypi/mackup

**Comment by VMatrix1900** [comment]
Great. I am thinking if we can seperate the application configuration and
the mackup logic program, so we can add support to new application without
release a new version of mackup?

**Comment by lra** [comment]
yep, that's something I have in mind. With a dedicated repo for all the supported apps. Added to the TODO
