### ISSUE TITLE
zsh and zpresto

### ISSUE THREAD

**Issue by ccorcos** [lra/mackup#580]
I can't figure out why my `.zprestorc` is being backed up. Its not listed in zsh.cfg.

**Comment by lra** [comment]
no idea, it's not listed in any file.
What's the full path and what is it linked to?

**Comment by ccorcos** [comment]
Nevermind!

https://github.com/sorin-ionescu/prezto/issues/912#issuecomment-117275280

**Comment by lra** [comment]
:+1:
