### ISSUE TITLE
Error: Unable to find your Google Drive install =(

### ISSUE THREAD

**Issue by warb2n** [lra/mackup#581]
hello! What i do wrong?

.mackup.cfg 
> [storage]
> engine = google_drive

Google drive have standard path 
>  /Users/b2n/Google Drive

**Comment by lra** [comment]
What's the output of `ls -l /Users/b2n/Library/Application Support/Google/Drive/sync_config.db /Users/b2n/Library/Application Support/Google/Drive/user_default/sync_config.db` ?

**Comment by warb2n** [comment]
![screen shot 2015-07-03 at 19 45 47](https://cloud.githubusercontent.com/assets/6230166/8502672/41284974-21bc-11e5-9431-eb1e7e1ad061.png)

**Comment by lra** [comment]
make sure you are running 0.8.6?

**Comment by warb2n** [comment]
➜  ~  mackup --version
Mackup 0.8.5

**Comment by lra** [comment]
0.8.6 is not yet in homebrew, not sure why. 0.8.6 fixes this, feel free to do a PR there.

**Comment by warb2n** [comment]
How install it manual? sry for my noobish =)
I found mackup in  /usr/local/Cellar/mackup/0.8.5 what i need to do?

**Comment by lra** [comment]
either wait for homebrew to update or install mackup using pip:
```
brew uninstall mackup
pip install mackup
```

**Comment by warb2n** [comment]
@lra 
Good all working now! I am happy =)
Have you any tricks for Keyboard>Shortcuts>App Shortcuts?
iCloud don't sync it, and i can't find any .plist

**Comment by lra** [comment]
I think we tried and removed it, I don't remember, you can try for yourself.
