### ISSUE TITLE
Reference shell environment variables from within app.cfg files

### ISSUE THREAD

**Issue by mkwmms** [lra/mackup#618]
Is it possible/would it be possible to reference `$XDG_CONFIG_HOME` etc. environment variables from within app.cfg files?

For example:
My `$XDG_CONFIG_HOME` is set to my iCloud Drive directory/.config (aka the ugly path: `~/Library/Mobile Documents/com~apple~CloudDocs/.config`)

So for .pythonrc it looks like:
```
[application]
name = Python

[configuration_files]
Library/Mobile Documents/com~apple~CloudDocs/.config/python/.pythonrc
```
But it would be awesome if it could look like:
```
[application]
name = Python

[configuration_files]
$XDG_CONFIG_HOME/.config/python/.pythonrc
```
or:
`os.environ['XDG_CONFIG_HOME']/python/.pythonrc`

This would also be helpful for apps that support custom environment variables like atom:
```
[application]
name = Atom

[configuration_files]

Library/Preferences/com.github.atom.plist
$ATOM_HOME/config.cson
$ATOM_HOME/init.coffee
$ATOM_HOME/keymap.cson
$ATOM_HOME/keymaps
$ATOM_HOME/snippets.cson
$ATOM_HOME/styles.less
```
__default app XDG support__
This would also be helpful for apps that support the XDG spec like git (see: the [git spec](http://git-scm.com/docs/git-config))
```
[application]
name = Git

[configuration_files]
$XDG_CONFIG_HOME/git/config
$XDG_CONFIG_HOME/git/credentials
$XDG_CONFIG_HOME/git/ignore
.gitignore
.gitcredentials
.gitconfig
```

**Comment by lra** [comment]
In your case it would work, but what about people that don't define `$XDG_CONFIG_HOME` ?

**Comment by mkwmms** [comment]
Am I wrong in thinking that you can specify multiple directory/files that "overlap" and mackup will only handle the ones that exist? 

Or are you saying mackup will throw an exception etc. if the variable is undefined rather than expanding it first, if set, and then checking the directories...

```
[application]
name = Git

[configuration_files]
$XDG_CONFIG_HOME/git/config
$XDG_CONFIG_HOME/git/credentials
$XDG_CONFIG_HOME/git/ignore
.gitignore
.credentials
.gitconfig
``` 
because it would be useless to specify both `$XDG_CONFIG_HOME/git/config` and a `.gitconfig` so mackup would backup either/or, but not both

**Comment by mkwmms** [comment]
[XDG spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)
[list of apps that support XDG](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support) and how they do (i.e. the differences in paths/files they support depending on if `$XDG_CONFIG_HOME` is set or not) - obviously you wouldn't need to maintain the .cfg files based on this list as user's could through PR but it is a handy link none-the-less

**Comment by lra** [comment]
I certainly prefer this version:
```
[application]
name = Git

[configuration_files]
$XDG_CONFIG_HOME/git/config
$XDG_CONFIG_HOME/git/credentials
$XDG_CONFIG_HOME/git/ignore
.gitignore
.gitcredentials
.gitconfig
```

The version with the `||` is just overkill and a pain to parse and handle.

I guess we could evaluate this `$XDG_CONFIG_HOME` but it breaks one of the rule of mackup: only relative path (to prevent stupid PRs trying to link things outside of home)

Maybe we could require that `$XDG_CONFIG_HOME` is a subfolder of home, but what if some dumb user set `$XDG_CONFIG_HOME` to /usr/share/I/dont/understand/unix. It's dumb but will surely happen.

**Comment by mkwmms** [comment]
Good points...
What if it was:
```
[application]
name = Git

[configuration_files]
git/config
git/credentials
git/ignore
.gitignore
.gitcredentials
.gitconfig
``` 
So the parser isn't changed at all (writing parsers suck) and the relative paths are not violated (because I agree this should be a `~` only thing...

BUT the only difference is:

1. if `$XDG_CONFIG_HOME` is set, look there for the files (thus finding `git/config`, `git/credentials`, `git/ignore`, and skipping the others)
2. look in `~` regardless of whether or not `$XDG_CONFIG_HOME` is set (finding nothing if `$XDG_CONFIG_HOME` is set but finding the normal .gitignore files if `$XDG_CONFIG_HOME` is not set)

I propose that if `$XDG_CONFIG_HOME` is set outside of `~` you could give the user a warning to proceed or just quit mackup etc. so we can handle the /usr/share/I/dont/understand/unix people haha

**Comment by lra** [comment]
That's interesting. Going one step further, what about:
```ini
[application]
name = Git

[home_config_paths]
.gitignore
.gitcredentials
.gitconfig

[xdg_config_paths]
git/config
git/credentials
git/ignore
```

**Comment by mkwmms** [comment]
I like that the best, and was actually my original idea I just thought it would deviate too far from the original setup... And it would be just an extra:
```
if os.environ['XDG_CONFIG_HOME']:
    self.apps[app_name]['xdg_config_files'].add(path)
```
which is not too bad! 

What if it was:
```
[application]
name = Git

[home_config_files]
.gitignore
.gitcredentials
.gitconfig

[xdg_config_files]
git/config
git/credentials
git/ignore
```
so it is closer to the original? I just want this XDG support to shake up as little as possible...

**Comment by lra** [comment]
you are right, let's go one step further to keep it backward compatible:
```ini
[application]
name = Git

[configuration_files]
.gitignore
.gitcredentials
.gitconfig

[xdg_configuration_files]
git/config
git/credentials
git/ignore
```
cool?

**Comment by mkwmms** [comment]
Even better.

**Comment by lra** [comment]
Cool, PR welcome.
