### ISSUE TITLE
0.8.8 Update Breaks in Homebrew

### ISSUE THREAD

**Issue by jonathanwren** [lra/mackup#620]
When I update to 0.8.8 through Homebrew, mackup stops working. 

I get the following error when I try to run any command: 

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.8/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.8', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.8/libexec/lib/python2.7/site-packages/mackup/main.py", line 52, in main
    if args['force']:
KeyError: 'force'
```

If I run without a command (just `mackup`), then I don't get the error. Same with `mackup -h` and `mackup --version`. But all of the commands choke with the same error.

When I switch back to 0.8.6, everything works as expected. 

I'm running Yosemite (10.10.3)

**Comment by lra** [comment]
Yep sorry about that, you'll have to do a PR there to submit 0.8.9 or stick to 0.8.6.
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/elb-tools.rb
You can also use pip to always get the latest version.
