### ISSUE TITLE
0.8.9 - 'Yes' to file replacement results in AssertionError

### ISSUE THREAD

**Issue by liamjones** [lra/mackup#621]
In 0.8.9 if I state Yes to an overwrite then I get an AssertionError. Answering No doesn't cause this and in previous versions I've been able to overwrite files fine.

```
mackup backup
Backing up /Users/liam.jones/Library/Preferences/XamarinStudio-5.0 ...
Backing up /Users/liam.jones/Library/Preferences/com.apple.symbolichotkeys.plist ...
Backing up /Users/liam.jones/.bashrc ...
Backing up /Users/liam.jones/Library/Containers/com.microsoft.rdc.mac/Data/Library/Preferences/com.microsoft.rdc.mac.plist ...
Backing up /Users/liam.jones/.ssh/config ...
A file named /Users/liam.jones/Dropbox/Mackup/.ssh/config already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>Yes
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.9/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.9', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.9/libexec/lib/python2.7/site-packages/mackup/main.py", line 62, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.9/libexec/lib/python2.7/site-packages/mackup/application.py", line 85, in backup
    utils.copy(filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.9/libexec/lib/python2.7/site-packages/mackup/utils.py", line 90, in copy
    assert os.path.exists(src)
AssertionError
```

**Comment by lra** [comment]
I guess it's due to a change in the ssh config: https://github.com/lra/mackup/commit/dcb26baf56f13330c069eadad35ac8feca7ac215#diff-3727ac8ad7f5a3d72f5ca92808b32f27
Can you try deleting the .ssh folder in dropbox and try again? (you can undelete in dropbox in case something goes wrong)

**Comment by liamjones** [comment]
I removed my ~/.ssh symlink, moved the .ssh directory back to my user home and re-ran mackup backup. Now it's not touching the .ssh directory or the files within it at all - nothing has been moved and replaced with symlinks.

**Comment by liamjones** [comment]
Okay, found it why it was doing nothing - when I had the assertion yesterday mackup had deleted my authorized_keys and config files (thus I wasn't seeing anything happen today since the only files Mackup looks for were missing).

I restored my config and authorized_keys from Time Machine and then re-ran mackup backup and it corrected moved and symlinked the two files.

**Comment by lra** [comment]
cool, glad you solved it. Migration between different configs are a pain we need to solve: https://github.com/lra/mackup/issues/229
