### ISSUE TITLE
Different backup paths in mackup.cfg for different machines

### ISSUE THREAD

**Issue by mkwmms** [lra/mackup#627]
What do you think of referencing environment variables and/or bringing XDG support to `mackup.cfg` and/or having an option to ignore your `mackup.cfg` and `.mackup` directory in the backup so you can have different paths to the mackup backup directory on different machines...?

For example:
```
[storage]
engine = file_system
directory = $XDG_CONFIG_HOME/dotfiles/mackup

[applications_to_ignore]
mackup
```

**Comment by lra** [comment]
> What do you think of referencing environment variables

Too fragile IMO, it will generate a lot of mistakes and thus support.

You can already ignore mackup, no?

**Comment by mkwmms** [comment]
My mistake, you can ignore mackup. I was being an idiot when I tested it. In that case that is good enough for me :) 

Also, when you get a chance I made some updates to #624
