### ISSUE TITLE
Sync arbitrary files

### ISSUE THREAD

**Issue by jmmk** [lra/mackup#641]
Is there currently a way to sync any file? For example, I keep my vim plugins listed in `.vimrc.bundles` so I would want to do something like `mackup backup .vimrc.bundles`.

**Comment by Joshfindit** [comment]
There are two mackup-standard ways of doing this:

1. If it's application-specific, [Create a new config file](https://github.com/lra/mackup/tree/master/doc#add-support-for-an-application-or-any-file-or-directory).
2. If it's a one-off, simply create the link yourself (`ln -s source ~/Dropbox/destination`)

**Comment by jmmk** [comment]
Thanks, that's perfect.
