### ISSUE TITLE
Error on restore on Sublime Text 3

### ISSUE THREAD

**Issue by rkpatel33** [lra/mackup#643]
I am getting this error when I run `mackup restore` when it tries to set the Sublime Text 3 settings. 

I originally did not have it installed and it failed un-gracefully, which I wasn't expecting. Then I installed it and got the same message.

Any ideas? I would have thought it would at lease continue with the rest of the install.

Error message -- http://note.io/1UI4Zig

**Comment by rkpatel33** [comment]
The issues was being caused my a link I had set manually to Dropbox from my previous system for keeping thing synced. Deleting it solved the problem.

Apparently the restore command does not anticipate that possibility.

**Comment by lra** [comment]
Sadly I don't see any easy way to anticipate this.

**Comment by Joshfindit** [comment]
I propose that if the destination checks positive for being a symlink, then skip that one, do the rest, and warn/remind the user so they can resolve it and run restore again.

**Comment by lra** [comment]
Sorry I don't understand the full scenario. We already check for links https://github.com/lra/mackup/blob/master/mackup/application.py#L154

**Comment by rkpatel33** [comment]
My scenario was just the following. Before running `mackup restore` the state of my sublime user settings folder was:

`[ST3 location].../Packages/User -> [some old manually set location on dropbox via symlink]`

Running `mackup restore` threw the error above. My solution to the issue was to

`$ rm [ST3 location].../Packages/User`

Then

`$mackup restore`

And all worked fine, it linked `[ST3 location].../Packages/User` to my settings that had already been synced to my `Dropbox/mackup` folder from my primary computer.

**Comment by lra** [comment]
I think you'd get a message with the current version asking you to delete the link if you want: https://github.com/lra/mackup/blob/master/mackup/application.py#L99

Were you using 0.8.11?

**Comment by rkpatel33** [comment]
Just did a brew install this week, version 0.8.5 looks like. But didn't see
that message. Odd.

____________
Rishi K. Patel

On Sep 14, 2015, at 12:50 PM, Laurent Raufaste <notifications@github.com>
wrote:

I think you'd get a message with the current version asking you to delete
the link if you want:
https://github.com/lra/mackup/blob/master/mackup/application.py#L99

Were you using 0.8.11?

—
Reply to this email directly or view it on GitHub
<https://github.com/lra/mackup/issues/643#issuecomment-140142126>.

**Comment by lra** [comment]
0.8.5 did not have this in place.

**Comment by rkpatel33** [comment]
Sorry misread than. Thanks!

On Monday, September 14, 2015, Laurent Raufaste <notifications@github.com>
wrote:

> 0.8.5 did not have this in place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lra/mackup/issues/643#issuecomment-140143223>.
>


-- 
______________________________________
Rishi K. Patel | Founder | *www.docnavapp.com <http://www.docnavapp.com>*
LinkedIn <https://www.linkedin.com/in/rkpatel33>
