### ISSUE TITLE
Mackup breaks Adobe Save for Web

### ISSUE THREAD

**Issue by hellopablo** [lra/mackup#644]
I noticed that when saving for Web in Adobe CC 2014 I'd get an error:

```
"Could not complete this operation. An unknown operating system error has occurred."
```

Resetting preferences etc didn't help, so I "undid" the Mackup backup and it started working again. Photoshop clearly didn't like the symlink.

Just dropping this here as a consideration for the developers as I realise that it might be more of an Adobe issue; I'm not sure if there _is_ a fix, or maybe it's a permission thing. Perhaps someone more enlightened than me can chip in.

**Comment by seandellis** [comment]
I'm having this same problem. It seems to be a permissions issue. I'm trying to fix it using the instructions at this link, but haven't had any luck. 

https://forums.adobe.com/thread/1184766

**Comment by hellopablo** [comment]
Closing abandoned issues / clearing my issues inbox.
