### ISSUE TITLE
Requesting support for OSX Automator service and other workflow backup

### ISSUE THREAD

**Issue by rkpatel33** [lra/mackup#661]
To the best of my knowledge, they are stored in the locations outlined here:

http://www.engadget.com/2012/12/17/where-automator-actions-and-workflows-live/

I am particularly concerned about these locations:

`~/Library/Services`
`/Library/Services`

But I am not sure what the ins and outs of backup these up might be so I did not attempt it myself.

**Comment by lra** [comment]
Well first we can't sync `/Library/Services`, it's not per user.
Regarding `~/Library/Services` I think I tried linking it and it screwed things up.
Unless Apple changed things, we can't.

**Comment by rkpatel33** [comment]
That's what I was afraid of. Thanks!
