### ISSUE TITLE
It would be helpful to see a list of all the links that Mackup has set up

### ISSUE THREAD

**Issue by rkpatel33** [lra/mackup#662]
I am trying to debug an issue with Sublime Text and thought it would be nice to see all the files in the Mackup directory and the files in the system that link back to them.

**Comment by lra** [comment]
you can use `ls`:
```bash
ls -l "Library/Application Support/Sublime Text 3/Packages/User"
```

**Comment by lra** [comment]
See https://github.com/lra/mackup/blob/master/mackup/applications/sublime-text-3.cfg

**Comment by arianmaykon** [comment]
I dont think this solve the "problem". @rkpatel33 just listed a example with the Sublime Text, but indeed would be nice to have a command to list the current versioned config directories.

Other question, if i add a supported software later, it will be automatically backup-ed?
