### ISSUE TITLE
For warning of mackup

### ISSUE THREAD

**Issue by sachin21** [lra/mackup#709]
Hi there.
I installed mackup and then I uninstalled it 3 days later.
Then I deleted the mackup folder.
so I noticed original .ssh/config file was deleted and .ssh/config was replaced as symbolic link.
I think mackup should warn users.

**Comment by lra** [comment]
I put as many warnings I felt were enough (e.g asking the user to confirm each action).
If you think the user should be more noticed, fee free to propose a PR.
