### ISSUE TITLE
Modify config to not move all files in a directory?

### ISSUE THREAD

**Issue by evansthompson** [lra/mackup#714]
I was looking at Dropbox thrashing and constantly working with Hazel files. It looks like there are 3 types of files primarily in the Application Support directory:

![image](https://cloud.githubusercontent.com/assets/172657/11153258/5244c364-89fd-11e5-8eb8-34a3a6e59cc1.png)

There are the `.hazelrules` and `.hazeldb` files.  There are also some lock files in there, but this is evidently the one point in time where Hazel isn't doing something with a file. 

Here's the current config:
```ini
[configuration_files]
Library/Application Support/Hazel
Library/Preferences/com.noodlesoft.Hazel.plist
```

While all the files are needed, the only ones that need to be backed up are the `.hazelrules`.  Would there be any way to just move and link those files? The `.hazelrules` don't change all that frequently, but `.hazeldb` files are modified every time Hazel runs a rule (I think). 

Here's another example for Expandrive. 

```ini
[configuration_files]
Library/Application Support/ExpanDrive
Preferences/com.expandrive.ExpanDrive2.plist
Preferences/com.expandrive.ExpanDrive3.plist
```

Looks fine. However, there are only a few files we need:

```bash
62c2798/
8q9tteo/
ExpanDrive4.ExpanDriveLicense
Expandrive.txt
expandrive4.favorites.js
expandrive5.favorites.js
frole7/
nloepl/
t17j0tg/
```
We need `.ExpanDriveLicense` of course, and the `.favorites.js`. All the directories are more like caches of the S3 buckets, OneDrive account, etc. Not stuff that needs to be backed up, and definitely not something that needs to live in Dropbox. My `ExpanDrive` folder under Application Support, for example is 150 MB.   Not totally massive, but the files needed are a mere 12k. 

I know I can create a custom application config, but I'm guessing almost anyone backing up similar apps are seeing the same thing; they just might not know it. 

I've already forked it (I think) to add some apps. I know there are specific files and directories to include. Are any sort of wildcards available? Like `*.hazelrules` or `*.plist`?

Thanks for an awesome, super-simple utility.  I also really like the (unintentional?) version control capabilities native to Dropbox etc. 

Evans

**Comment by lra** [comment]
I totally agree, and have to trust people who submit config as I can't try every application support out there.
If you have a better config for some app (better config = list of explicit files to sync instead of a whole folder) please submit a PR, it will be more than welcome.

There is nothing like wildcard, it's just files and folders. TODO is here: https://github.com/lra/mackup/issues/602

Thanks!

**Comment by itsBREX** [comment]
> I was looking at Dropbox thrashing and constantly working with Hazel files. It looks like there are 3 types of files primarily in the Application Support directory:
> 
> ![image](https://cloud.githubusercontent.com/assets/172657/11153258/5244c364-89fd-11e5-8eb8-34a3a6e59cc1.png)
> 
> There are the `.hazelrules` and `.hazeldb` files. There are also some lock files in there, but this is evidently the one point in time where Hazel isn't doing something with a file.
> 
> Here's the current config:
> 
> ```ini
> [configuration_files]
> Library/Application Support/Hazel
> Library/Preferences/com.noodlesoft.Hazel.plist
> ```
> 
> While all the files are needed, the only ones that need to be backed up are the `.hazelrules`. Would there be any way to just move and link those files? The `.hazelrules` don't change all that frequently, but `.hazeldb` files are modified every time Hazel runs a rule (I think).
> 
> Here's another example for Expandrive.
> 
> ```ini
> [configuration_files]
> Library/Application Support/ExpanDrive
> Preferences/com.expandrive.ExpanDrive2.plist
> Preferences/com.expandrive.ExpanDrive3.plist
> ```
> 
> Looks fine. However, there are only a few files we need:
> 
> ```shell
> 62c2798/
> 8q9tteo/
> ExpanDrive4.ExpanDriveLicense
> Expandrive.txt
> expandrive4.favorites.js
> expandrive5.favorites.js
> frole7/
> nloepl/
> t17j0tg/
> ```
> 
> We need `.ExpanDriveLicense` of course, and the `.favorites.js`. All the directories are more like caches of the S3 buckets, OneDrive account, etc. Not stuff that needs to be backed up, and definitely not something that needs to live in Dropbox. My `ExpanDrive` folder under Application Support, for example is 150 MB. Not totally massive, but the files needed are a mere 12k.
> 
> I know I can create a custom application config, but I'm guessing almost anyone backing up similar apps are seeing the same thing; they just might not know it.
> 
> I've already forked it (I think) to add some apps. I know there are specific files and directories to include. Are any sort of wildcards available? Like `*.hazelrules` or `*.plist`?
> 
> Thanks for an awesome, super-simple utility. I also really like the (unintentional?) version control capabilities native to Dropbox etc.
> 
> Evans

I just did a ```mackup restore```  on a new machine and now my original machine's Hazel is completely empty (list of folders + rules in the app). Haz this every happened to you? Any fix?
