### ISSUE TITLE
All application settings deleted

### ISSUE THREAD

**Issue by asvc** [lra/mackup#716]
Not sure what exactly just happened, but I ran the tool, it created the backup of all settings and after I've deleted that backup folder, (almost) all programs were suddenly reset to their defaults. Needless to say reinstalling OSX wasn't exactly my plan for today, but with thanks to `mackup` life becomes more interesting.

**Comment by lra** [comment]
Well, I'm guessing here because your description is not explicit enough, but sounds like you deleted the folder where Mackup links all config files manually, which means that you deleted all the settings files of your app.

Not sure what you expect from this issue.

**Comment by asvc** [comment]
I was expecting it copies the settings. Anyway, how original settings were deleted if mackup actually (sym)linked them?

**Comment by asvc** [comment]
I should have read https://github.com/lra/mackup#backup before deleting the `mackup` folder. Actually before doing `brew install mackup`, but that's another story.

**Comment by lra** [comment]
if you deleted the folder where mackup put the linked files, u deleted it, not mackup.
You can undelete files in dropbox, so you should be able to recover.
