### ISSUE TITLE
how to make mackup look for Dropbox instead of Dropbox (Personal)

### ISSUE THREAD

**Issue by codepreneur** [lra/mackup#722]
I had Dropbox, but then after being added to a business dropbox account, dropbox renamed Dropbox into Dropbox (Personal) and thats when I installed mackup, however after I removed that business part, Dropbox renamed the folder back to Dropbox and now after I renamed Dropbox (Personal) into Dropbox all my configuration files such as `.vimrc` became empty...

Is there a better solution than this?
```
ln -s /location/to/link linkname
Later

ln -s /location/to/link2 newlink
mv newlink linkname
```

**Comment by QuinnyPig** [comment]
Dropbox should automatically symlink `~/Dropbox (Personal)` into `~/Dropbox` when you link a personal account; are you not seeing this?

**Comment by lra** [comment]
Yes, after you link `Dropbox (Personal)` to `Dropbox`, you can run `mackup uninstall` to unlink everything which will move back all the files into your home, then `mackup backup` to link back the files into dropbox using the legit name.

You can then delete the old `Dropbox (Personal)` link.
