### ISSUE TITLE
Disable syncing of .netrc file

### ISSUE THREAD

**Issue by LandonSchropp** [lra/mackup#730]
Mackup seems to be syncing the `~/.netrc`file. Like the `.ssh` directory, this file contains sensitive passwords I wouldn't like shared between computers. I think the same arguments in #512 and #336 apply here, and I'd like to see it disabled by default. Barring that, I'd like a way to turn it off for myself.

**Comment by vitorgalvao** [comment]
[Docs to ignore applications](https://github.com/lra/mackup/tree/master/doc#dont-sync-an-application).

**Comment by LandonSchropp** [comment]
Ah, I missed that in the readme. Thanks!

**Comment by lra** [comment]
thx @vitorgalvao
