### ISSUE TITLE
vscode and atom lose their extensions/packages

### ISSUE THREAD

**Issue by openingnow** [lra/mackup#732]
Brackets' extensions are backed up as they are stored under Library/Application Support/Brackets with other preferences.
However vscode stores its extension under ~/.vscode/extensions, which is not listed in vscode.cfg.
Similarly atom store those at ~/.atom/packages and losses them after restoring .

As their extensions are not controlled by other tools, including them would be better.

**Comment by maxim-lian** [comment]
I have the opposite problem: mackup _is_ storing `.vscode/extensions`, and taking up 570MB. 

Storing the settings file would be enough to reinstall the extensions, I believe?

**Comment by openingnow** [comment]
Well, that feature has been added 2 month ago(#1071, [commit](https://github.com/lra/mackup/blame/35e531e944825e8e3f2a6626a247d0baab778d6a/mackup/applications/vscode.cfg)) and I think it is needed but 570MB is so large.. Isn't the `extensions` directory contains duplicated extensions?

**Comment by maxim-lian** [comment]
For example, this is the gist that is backed up by Sync Settings (as VSCode Extension): https://gist.github.com/maxim-lian/a6e11de8576124611433e1808940d90f

That has all the extension data without needing the full extension library

**Comment by mustafawm** [comment]
Any update regarding this issue?
I have the same problem as @max-sixty (it's actually taking more than 700 MB!)

**Comment by chuckd** [comment]
For anyone confused like I was for a while: syncing of extensions was merged in March 2018 (#1071) then reverted not long after (#1170).
