### ISSUE TITLE
Skype mackup prevents login storage

### ISSUE THREAD

**Issue by michaelaye** [lra/mackup#771]
Thanks for this utility!

Had to block Skype from being macked-up though, as it lost the login on both of my machines every time I'd close the app.

**Comment by TCattd** [comment]
https://github.com/lra/mackup/pull/785

**Comment by lra** [comment]
Yep, Skype support has been removed like stated by @TCattd .
I'll do a release in the next days, but I'd keep it ignored in the meantime.
