### ISSUE TITLE
Need support for /Library/LaunchDaemons/ folder.

### ISSUE THREAD

**Issue by xykong** [lra/mackup#779]
It seems that mackup doesn't support files outside the home folder.
I tried to add files in /Library/LaunchDaemons/ to mackup config files like the following methord:

```
[application]
name = autossh

[configuration_files]
/Library/LaunchDaemons/com.xykong.autossh.plist
```
```
➜  .mackup  mackup backup -v
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.12/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.12', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/appsdb.py", line 53, in __init__
    .format(path))
ValueError: Unsupported absolute path: /Library/LaunchDaemons/com.xykong.autossh.plist
```

##### then i tried relative path:

```
[application]
name = autossh

[configuration_files]
../../Library/LaunchDaemons/com.xykong.autossh.plist
```
##### no errors. But the file in my Dropbox is also in the relative path。
```
/Users/kongxiangyi/Dropbox/Library/LaunchDaemons/com.xykong.autossh.plist
/Users/kongxiangyi/Dropbox/Workspace/Mackup
```

**Comment by lra** [comment]
Syncing outside of the user home is not supported for zillions of reasons, sorry.
I suggest contacting the developer of the application you use to let him know to not install user configuration outside of the home folder.

**Comment by mrahmadt** [comment]
This should be supported, I believe people who create their own configuration are capable of taking care not to break their system.

:)
