### ISSUE TITLE
Issue backing up Xcode plugins

### ISSUE THREAD

**Issue by Entalpi** [lra/mackup#789]
![screen shot 2016-03-27 at 21 35 32](https://cloud.githubusercontent.com/assets/1652130/14067423/f074ced6-f464-11e5-8995-2a20da615173.jpg)

Just did a normal 'mackup backup' to Google Drive for the first time; any pointers?

**Comment by ChristianBagley** [comment]
Seems to be a permissions issue for that file. The file (and likely directory) is probably set to read-only, you can use chmod to change the permissions and it should work after that.

**Comment by Entalpi** [comment]
I tried changing the permission on the folder (and it's subfolders) to 777 but it did not work so I just ended up deleting it. Sorry for wasting your time. :-1:
