### ISSUE TITLE
Prevent Skype from synching

### ISSUE THREAD

**Issue by edge0703** [lra/mackup#803]
How can I prevent Skype from syncing to Mackup? I already tried to move all the settings files from "/Dropbox/mackup/library/application support/skype" to "/Library/Application Support/skype", but shortly after that the folder in Dropbox is created again. What drives me especially crazy here is that "config.xml" is synced every few minutes, so I have to switch off "Dropbox syncing" because this dialog is driving me crazy!

**Comment by vitorgalvao** [comment]
[Docs](https://github.com/lra/mackup/tree/master/doc#dont-sync-an-application).

**Comment by lra** [comment]
Skype support has been removed in 0.8.14. Sorry about that.

**Comment by edge0703** [comment]
Well, that doesn't solve my problem. How can I stop "mackup" from syncing this damn folder? I tried it with the ".mackup.cfg" config file for now, hope that helps.

**Comment by edge0703** [comment]
Nope, didn't help, this damn "config.xml" is still being synced every few minutes.

**Comment by lra** [comment]
You need to remove the link.
Mackup just does create links, it does not syncs.
Delete the links that point to Dropbox and it won't save those in dropbox anymore.

If you really don't know how to, last resort is to install the version of mackup you used when syncing skype, and run mackup uninstall, it will put everything back into place.
