### ISSUE TITLE
Box Sync ignores files that start with a dot

### ISSUE THREAD

**Issue by katherinelim** [lra/mackup#807]
Mackup creates the backup folder in the Box Sync local folder properly and all dot files (.bash_profile, .bashrc, .gitconfig, etc.) are copied there but they are never synced to Box, which means that after the local Box Sync folder is deleted, the dot files will not be restored from Box.

This is due to Box Sync ignoring files that start with a dot "." as hidden files.

Documented here: [https://community.box.com/t5/Box-Sync/Which-File-Types-Are-Ignored-Or-Blocked-In-Box-Sync/ta-p/117](https://community.box.com/t5/Box-Sync/Which-File-Types-Are-Ignored-Or-Blocked-In-Box-Sync/ta-p/117)

The way around this could involve copying the files to names that do not start with a dot and creating symlinks back to the original dot file names, e.g., .bashrc -> Box Sync/Mackup/bashrc.txt

**Comment by lra** [comment]
Wow, that's really stupid...

OK, I guess the box engine needs to rename those files to something line `.bashrc -> box_dot_bashrc_`.
That could work for individual files, but if a linked folder contains dotfiles, mackup cannot help here.

Not sure if there are a lot of dotfiles in folders, but it's a possible source of bugs and confusion.

Also what about dot folders? Same behavior? Sounds like there is no easy fix on mackup side. Is there a way to ask box if they could make this an option? (ignoring dot files)

**Comment by katherinelim** [comment]
It looks messy to implement. Given that Dropbox is ok with dotfiles, am happy to close this as a dontfix and take it up with Box.

**Comment by lra** [comment]
The problem is that it's a valid issue... Should we just drop Box's support?

**Comment by katherinelim** [comment]
Dropping Box support would suffice, but leave a note as to why, it's going to become a frequently asked question. 👍

**Comment by silvamerica** [comment]
Are there any updates that might make this work? Box is still listed as Supported Storage.

**Comment by lra** [comment]
I'm on it, I'm removing Box support altogether.

**Comment by brandondrew** [comment]
Wow, adding Box to my mental shit list of products to avoid in general.  How can a file storage product be any good that ignores a huge class of important files?  This is really mind-boggling.

**Comment by SeniorMars** [comment]
Could you readd it back? I am sure it works as I have used it with rclone.

**Comment by lra** [comment]
A contributor could, but it would require tests to make sure this works, as I can't spend the time on testing it.

**Comment by devnoname120** [comment]
@SeniorMars And it could be an exclusion caused by their desktop app, so the fact that rclone works doesn't mean that this issue is solved on the Box synchronization software.
