### ISSUE TITLE
Atom Package Sync file not working

### ISSUE THREAD

**Issue by joshmedeski** [lra/mackup#824]
I've added the following file to my settings:

```
[configuration_files]
.atom/packages.cson
```

But when I run the mackup commands it doesn't work. Could there be a conflict between the atom Mackup settings and this file? Could I add this file to the .atom file and make a PR. I'm using the [package-sync](https://atom.io/packages/package-sync) package to sync my packages.

**Comment by pszaro** [comment]
Did you try using 

~/.atom/packages.cson in your config file?

**Comment by joshmedeski** [comment]
No, I'll try that and let you know what it says.

**Comment by joshmedeski** [comment]
Things seem to be working fine once I put them in a `.cfg` file in the `.mackup` folder 😄

**Comment by ursbraem** [comment]
I'm not sure if I get this right: if I want mackup (thanks!) to sync my atom packages too, I need to add the `packages.cson` to `.mackup.cfg`? 

My Config file (in `my_settings/Mackup` and with a symlink that Mackup probably created at the first run in the home dir) now looks like this:

```
[storage]
engine = file_system
path = my_settings

[configuration_files]
~/.atom/packages.cson
```

Should that work (it hasn't done so yet) and is it required to add that line to sync atom packages?

**Comment by ursbraem** [comment]
Ok, of course the packages list has to exist before you can sync it.
Create it with https://atom.io/packages/package-sync or `apm list --installed --bare > packages.cson` (cf. https://discuss.atom.io/t/installed-packages-list-into-single-file/12227)

To install the packages in that list on the second system, I understand that you have to use `apm install --packages-file packages.cson` then

**Comment by ursbraem** [comment]
Also, if you want to add custom config files for an app, in my case atom, I understood that you have to create ~/.mackup/atom.cfg, copy over everything from https://github.com/lra/mackup/blob/master/mackup/applications/atom.cfg to that file, and then add your desired additionoal files.

Seems to work now!

So: To sync atom packages:

* Make atom write a list of installed packages with `apm list --installed --bare > packages.cson` or similar
* teach mackup to sync them with a custom .cfg file
* install packages on synced devices with `install --packages-file packages.cson `

**Comment by cappadona** [comment]
Thanks @ursbraem...big help. Instead of overriding mackup's default `atom.cfg`, I just added a separate config file for keeping packages in sync, as [described in the docs](https://github.com/lra/mackup/tree/master/doc#add-support-for-an-application-or-any-file-or-directory).

`~/.mackup/atom-packages.cfg`
```
[application]
name = Atom Packages

[configuration_files]
.atom/packages.cson
```
