### ISSUE TITLE
Usage help

### ISSUE THREAD

**Issue by FezVrasta** [lra/mackup#867]
I really like this app but I'm not sure if I understood how it works.

I have ran `mackup backup` on my iMac and ran `mackup restore` on my MacBook.

Do I have to do anything to keep them in sync or they will do everything automatically?

If I install a new app, is the preference automatically backuped or do I have to do something?

**Comment by FezVrasta** [comment]
Anyone?

**Comment by fotan** [comment]
I actually have the exact same question...

**Comment by bbohling** [comment]
While I have not used this app, I am exploring so have read the [documentation](https://github.com/lra/mackup) (including the [config stuff](https://github.com/lra/mackup/blob/master/doc/README.md)). This is my understanding:

>Do I have to do anything to keep them in sync or they will do everything automatically?

No, `mackup backup` copies the app file(s) to a central location (e.g., Dropbox) and then creates a symlink (virtual link to the central location). As long as each computer you use mackup on has the same central service (e.g., Dropbox), the files will stay in sync. [These are the supported storage services](https://github.com/lra/mackup#supported-storages).

>If I install a new app, is the preference automatically backuped or do I have to do something?

No. You will have to run `mackup backup` again. **If** mackup [supports the app](https://github.com/lra/mackup#supported-applications), it will copy the preferences to the central location.
