### ISSUE TITLE
Uninstall specific app?

### ISSUE THREAD

**Issue by aristidesfl** [lra/mackup#872]
Is there a way to uninstall just one specific app?

**Comment by lra** [comment]
I guess you can uninstall it, ignore an app (see https://github.com/lra/mackup/tree/master/doc#dont-sync-an-application) and backup again.

**Comment by aristidesfl** [comment]
Isn't that recipe for trouble? when you uninstall on  other machines the app will be already ignored and thus not uninstalled.

**Comment by lra** [comment]
yes it is, it needs to be manually handled.

**Comment by aristidesfl** [comment]
Maybe we should have a mechanism to handle this situation better. For example we could store a backups of the config file, and when changes are detected (like apps removed from the config), the  restore/uninstall could handle things more gracefully.

**Comment by lra** [comment]
yes, it's doable, not easy.
