### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by orschiro** [lra/mackup#912]
Dear all, 

When is a new version going to be released?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/20237866/b211e51e-a8de-11e6-9af5-2d411df94ec4.png)

**Comment by lra** [comment]
Soon ;)

Sorry about the delay, maintainers help needed!

**Comment by orschiro** [comment]
Cool, thanks for the new release! :-)
