### ISSUE TITLE
Plans to check out PRs?

### ISSUE THREAD

**Issue by sallar** [lra/mackup#917]
Hi, 

There are currently 84 open Pull Requests. Including mine #812 which I made a long time ago. It seems that the author or authors have no intention of checking out any of the PRs, commenting on them or at the very least, closing them.

If this is the case, I'd love to make a fork and actively maintain that, so at least people don't have to wait this long for any kind of change. I also can be a maintainer on this repo.

Thanks!

**Comment by MadeOfMagicAndWires** [comment]
I'm all for it, especially considering some issues have like 3 separate PRs because none of them have been merged.

**Comment by lra** [comment]
Hi,

> It seems that the author or authors have no intention of checking out any of the PRs, commenting on them or at the very least, closing them.

Don't assume things like this, yes the ration of contributions vs maintainers is unbalanced, but I'm looking for maintainers to help me. Contact me of you are interested.

The last PR merged was 2 days ago, sorry but I have other priorities sometimes =) Any help welcome as long as people are serious.
