### ISSUE TITLE
Prefs outside user path ?

### ISSUE THREAD

**Issue by melMass** [lra/mackup#918]
Hi Ira, 

Awesome tool, I've made a lot of new cfg files for me (Latest Adobe versions, Sketch, and other apps). It runs perfectly.
Now I have questions: 
- How does one copy prefs from **outside the user folder** ? (for instance /Applications/ in my case).
- Is there a way to fetch data from Cloud without symlinking ? (I have 3 computers but would like only the main one to update the prefs on the cloud, and the others to fetch them. The current workflow assumes all computer update the prefs right ?).
 - Would it be hard to had shell script to the process ? For instance brew list > Mackup/brew_list.sh
or apt-get list > apt_list.sh, That would make it the absolute backup solution for preferences 💯

**Comment by melMass** [comment]
So I tried absolute paths, and mackup complains about absolute path of course :)
One last question and Mackup will be mystery less to me,
What does the name application in the cfg file do ?

**Comment by lra** [comment]
Hi,

Glad you love the tool, please help improving it ;)

> How does one copy prefs from outside the user folder ?

It is not supported, Mackup is all about user config, and there is no easy way to solve conflicts if it's start messing with other files on the system. (e.g. 2 users using Mackup)

Any sane application should save its config in the user folder anyway.

> Is there a way to fetch data from Cloud without symlinking ?

No, it will be possible once the copy system is done: https://github.com/lra/mackup/issues/613

> Would it be hard to had shell script to the process ? For instance brew list > Mackup/brew_list.sh or apt-get list > apt_list.sh, That would make it the absolute backup solution for preferences 

Not sure I understand, sorry.

> What does the name application in the cfg file do ?

It just the "display" name vs the "internal" name of the filename.

**Comment by melMass** [comment]
Great #613 will actually clear all the problems I have (I almost screwed my system by adding a Sandboxed container to Mackup, resulting in symlinking my Desktop, Library, Documents folder to mackup, because there was symlinks of them in the container.), 
By the way do you think there could be a workaround ? Because in order to symlink a container, OSX's limit is that you need to symlink the entire container otherwise it breaks the host app, but as I experimented doing that in mackup will copy the content of contained symlinks. Can't mackup just symlink to the same elements on it's own ?

For the shell script thing, I simply meant adding like a script tag to the cfg files to be executed, either before or after backup, allowing extra customisation. The example I was refering to was simply to sync a list of packages across different computers.

**Comment by lra** [comment]
> By the way do you think there could be a workaround ?

Not that I know of.

> For the shell script thing, I simply meant adding like a script tag to the cfg files to be executed, either before or after backup, allowing extra customisation. The example I was refering to was simply to sync a list of packages across different computers.

Not on the roadmap, I don't think it's gonna be used to a lot of people and it would be super complex and super dangerous.

**Comment by melMass** [comment]
> Not that I know of.

 
Then I think it should be stated clearly as it can **mess up a system quite badly**, same for the defaults, I think **by default** mackup backup should **not backup anything** unless specified in the mackupcfg file (something like `use all`), at least until the copy system is done.

> Not on the roadmap, I don't think it's gonna be used to a lot of people and it would be super complex and super dangerous.

Yes you are right, I've actually simply created a script for my main worsktation that do all that I need before `mackup backup`.
How can we contribute to the config files ?

**Comment by lra** [comment]
> Then I think it should be stated clearly as it can mess up a system quite badly, same for the defaults, I think by default mackup backup should not backup anything unless specified in the mackupcfg file (something like use all), at least until the copy system is done.

https://github.com/lra/mackup/issues/614

Feel free to PR if the doc is not clear enough, I'm not a fan of big warnings messages all over the place.

> How can we contribute to the config files ?

https://github.com/lra/mackup/blob/master/CONTRIBUTING.md
