### ISSUE TITLE
Add support for Amphetamine

### ISSUE THREAD

**Issue by LandonSchropp** [lra/mackup#928]
Amphetamine is a great little replacement for Caffeine. It would be great to be able to sync the settings for it.

**Comment by evansthompson** [comment]
Amphetamine is from the MAS, right? I didn't think those apps were supported.  It looks like the preferences, though, are in `~/Library/Containers/com.if.Amphetamine/Data/Library/Preferences/com.if.Amphetamine.plist`

**Comment by LandonSchropp** [comment]
Yep, it's in the App Store.

**Comment by LandonSchropp** [comment]
Thanks!
