### ISSUE TITLE
This app should come with a HUGE warning.

### ISSUE THREAD

**Issue by MichMich** [lra/mackup#973]
I don't want to be that guy ... I don't want to be a PITA, but in my honest opinion this app should come with a HUGE warning.

Somehow, the backup failed, or the dropbox folder disappeared a few seconds after I made my initial mackup backup. Resulting in all broken symbolic links in my settings. Essentially I lost ALL my settings.

Since restoring every single settings file manually is undoable, I'm now recovering my full system via TimeMachine ...

I understand that the failure might not be caused by Mackup. But messing with all stored settings on a machine should not be taken lightly.

**Comment by lra** [comment]
I'm pretty transparent about what it does: https://github.com/lra/mackup#what-does-it-do

 What do you suggest? Popups? Slapping the user face with my hand coming out of your screen?
Every  action needs to be confirmed already, and it's annoying for the regular users.

**Comment by lra** [comment]
Also I don't understand what it could have deleted neither what happened in your case. Sorry for your loss, but as you said, Mackup is moving files into dropbox, that's it.

**Comment by MichMich** [comment]
I think a good approach would be to let the user decide which apps he want's to 'Mackup'. That way I could have tried it for a while. Not saying this to be an annoying user, just to save others a major headache.

Did not really record the issue, but what I do remember is that it exited with an error due to something in my Xcode folder. 

Fun fact, it turned out my time machine had an issue as well, so had to reinstall my Mac after this incident and start from scratch. ¯\_(ツ)_/¯

**Comment by vitorgalvao** [comment]
> I think a good approach would be to let the user decide which apps he want's to 'Mackup'.

[You can](https://github.com/lra/mackup/blob/master/doc/README.md#only-sync-one-or-two-application).

**Comment by MichMich** [comment]
Nice. But in IMHO it would be much better if this was faked when running the quick install:

    # Install Mackup
    brew install mackup

    # Launch it and back up your files
    mackup backup

Which results in something like ...

> Do you want to select which apps you would like to backup, or do you want to backup everything? [All/Select] A
> 
> Warning: this will move all your settings to you dropbox folder. Symbolic links will be placed on it's original location. Are you sure you want to continue? [Yes/No]

This would have probably saved my ass ...
