### ISSUE TITLE
How to ignore (only) ~/.fonts directory

### ISSUE THREAD

**Issue by akirak** [lra/mackup#992]
Hello, I am using Linux, and my problem is as follows:

- I want to track ~/.Xmodmap.
- I don't want to track ~/.fonts. 

Both of these items seems to be part of `x11` application, so if I add `x11` application to `applications_to_ignore` in order to ignore ~/.fonts, Mackup won't track ~/.Xmodmap. Is there a way to ignore ~/.fonts directory while keeping .Xmodmap under tracking?

**Comment by akirak** [comment]
You can solve this issue by creating a separate "application" configuration file for tracking any file which is part of `x11` profile, as in https://github.com/akirak/user-admin/blob/master/files/dotfiles/.mackup/xinitrc.cfg

Actually, I am no longer using mackup to track Xmodmap.

**Comment by Kol9yN** [comment]
Bump, actual request about .fonts folder
@lra possible to fit by some way please?
